// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameFile = "files"

// File mapped from table <files>
type File struct {
	ID            int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // id
	CreatedAt     time.Time      `gorm:"column:created_at" json:"created_at"`               // 创建时间
	UpdatedAt     time.Time      `gorm:"column:updated_at" json:"updated_at"`               // 更新时间
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`               // 删除时间
	CreatedBy     int64          `gorm:"column:created_by" json:"created_by"`               // 创建者ID
	UpdatedBy     int64          `gorm:"column:updated_by" json:"updated_by"`               // 更新者ID
	DeletedBy     int64          `gorm:"column:deleted_by" json:"deleted_by"`               // 删除者ID
	Remark        string         `gorm:"column:remark" json:"remark"`                       // 备注
	TenantID      int64          `gorm:"column:tenant_id" json:"tenant_id"`                 // 租户ID
	Provider      string         `gorm:"column:provider" json:"provider"`                   // OSS供应商
	BucketName    string         `gorm:"column:bucket_name" json:"bucket_name"`             // 存储桶名称
	FileDirectory string         `gorm:"column:file_directory" json:"file_directory"`       // 文件目录
	FileGUID      string         `gorm:"column:file_guid" json:"file_guid"`                 // 文件Guid
	SaveFileName  string         `gorm:"column:save_file_name" json:"save_file_name"`       // 保存文件名
	FileName      string         `gorm:"column:file_name" json:"file_name"`                 // 文件名
	Extension     string         `gorm:"column:extension" json:"extension"`                 // 文件扩展名
	Size          int64          `gorm:"column:size" json:"size"`                           // 文件字节长度
	SizeFormat    string         `gorm:"column:size_format" json:"size_format"`             // 文件大小格式化
	LinkURL       string         `gorm:"column:link_url" json:"link_url"`                   // 链接地址
	Md5           string         `gorm:"column:md5" json:"md5"`                             // md5码，防止上传重复文件
}

// TableName File's table name
func (*File) TableName() string {
	return TableNameFile
}
