// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameInternalMessageRecipient = "internal_message_recipients"

// InternalMessageRecipient mapped from table <internal_message_recipients>
type InternalMessageRecipient struct {
	ID              int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // id
	CreatedAt       time.Time      `gorm:"column:created_at" json:"created_at"`               // 创建时间
	UpdatedAt       time.Time      `gorm:"column:updated_at" json:"updated_at"`               // 更新时间
	DeletedAt       gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`               // 删除时间
	TenantID        int64          `gorm:"column:tenant_id" json:"tenant_id"`                 // 租户ID
	MessageID       int64          `gorm:"column:message_id" json:"message_id"`               // 站内信内容ID
	RecipientUserID int64          `gorm:"column:recipient_user_id" json:"recipient_user_id"` // 接收者用户ID
	Status          string         `gorm:"column:status" json:"status"`                       // 消息状态
	ReceivedAt      time.Time      `gorm:"column:received_at" json:"received_at"`             // 消息到达用户收件箱的时间
	ReadAt          time.Time      `gorm:"column:read_at" json:"read_at"`                     // 用户阅读消息的时间
}

// TableName InternalMessageRecipient's table name
func (*InternalMessageRecipient) TableName() string {
	return TableNameInternalMessageRecipient
}
