// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameInternalMessage = "internal_messages"

// InternalMessage mapped from table <internal_messages>
type InternalMessage struct {
	ID         int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // id
	CreatedAt  time.Time      `gorm:"column:created_at" json:"created_at"`               // 创建时间
	UpdatedAt  time.Time      `gorm:"column:updated_at" json:"updated_at"`               // 更新时间
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`               // 删除时间
	CreatedBy  int64          `gorm:"column:created_by" json:"created_by"`               // 创建者ID
	UpdatedBy  int64          `gorm:"column:updated_by" json:"updated_by"`               // 更新者ID
	DeletedBy  int64          `gorm:"column:deleted_by" json:"deleted_by"`               // 删除者ID
	TenantID   int64          `gorm:"column:tenant_id" json:"tenant_id"`                 // 租户ID
	Title      string         `gorm:"column:title" json:"title"`                         // 消息标题
	Content    string         `gorm:"column:content" json:"content"`                     // 消息内容
	SenderID   int64          `gorm:"column:sender_id" json:"sender_id"`                 // 发送者用户ID
	CategoryID int64          `gorm:"column:category_id" json:"category_id"`             // 分类ID
	Status     string         `gorm:"column:status;default:DRAFT" json:"status"`         // 消息状态
	Type       string         `gorm:"column:type;default:NOTIFICATION" json:"type"`      // 消息类型
}

// TableName InternalMessage's table name
func (*InternalMessage) TableName() string {
	return TableNameInternalMessage
}
