// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameInternalMessageCategory = "internal_message_categories"

// InternalMessageCategory mapped from table <internal_message_categories>
type InternalMessageCategory struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // id
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`               // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`               // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`               // 删除时间
	CreatedBy int64          `gorm:"column:created_by" json:"created_by"`               // 创建者ID
	UpdatedBy int64          `gorm:"column:updated_by" json:"updated_by"`               // 更新者ID
	DeletedBy int64          `gorm:"column:deleted_by" json:"deleted_by"`               // 删除者ID
	IsEnabled bool           `gorm:"column:is_enabled;default:true" json:"is_enabled"`  // 是否启用
	SortOrder int32          `gorm:"column:sort_order" json:"sort_order"`               // 排序顺序，值越小越靠前
	Remark    string         `gorm:"column:remark" json:"remark"`                       // 备注
	TenantID  int64          `gorm:"column:tenant_id" json:"tenant_id"`                 // 租户ID
	Name      string         `gorm:"column:name" json:"name"`                           // 名称
	Code      string         `gorm:"column:code" json:"code"`                           // 编码
	IconURL   string         `gorm:"column:icon_url" json:"icon_url"`                   // 图标URL
	ParentID  int64          `gorm:"column:parent_id" json:"parent_id"`                 // 父节点ID
}

// TableName InternalMessageCategory's table name
func (*InternalMessageCategory) TableName() string {
	return TableNameInternalMessageCategory
}
