// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysDictEntry = "sys_dict_entries"

// SysDictEntry mapped from table <sys_dict_entries>
type SysDictEntry struct {
	ID           int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // id
	CreatedAt    time.Time      `gorm:"column:created_at" json:"created_at"`               // 创建时间
	UpdatedAt    time.Time      `gorm:"column:updated_at" json:"updated_at"`               // 更新时间
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`               // 删除时间
	CreatedBy    int64          `gorm:"column:created_by" json:"created_by"`               // 创建者ID
	UpdatedBy    int64          `gorm:"column:updated_by" json:"updated_by"`               // 更新者ID
	DeletedBy    int64          `gorm:"column:deleted_by" json:"deleted_by"`               // 删除者ID
	Description  string         `gorm:"column:description" json:"description"`             // 描述
	SortOrder    int32          `gorm:"column:sort_order" json:"sort_order"`               // 排序顺序，值越小越靠前
	IsEnabled    bool           `gorm:"column:is_enabled;default:true" json:"is_enabled"`  // 是否启用
	TenantID     int64          `gorm:"column:tenant_id" json:"tenant_id"`                 // 租户ID
	EntryLabel   string         `gorm:"column:entry_label" json:"entry_label"`             // 字典项的显示标签
	EntryValue   string         `gorm:"column:entry_value" json:"entry_value"`             // 字典项的实际值
	NumericValue int32          `gorm:"column:numeric_value" json:"numeric_value"`         // 数值型值
	LanguageCode string         `gorm:"column:language_code" json:"language_code"`         // 语言代码
	TypeID       int64          `gorm:"column:type_id;not null" json:"type_id"`
}

// TableName SysDictEntry's table name
func (*SysDictEntry) TableName() string {
	return TableNameSysDictEntry
}
