// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysMenu = "sys_menus"

// SysMenu mapped from table <sys_menus>
type SysMenu struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`               // id
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`                             // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`                             // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`                             // 删除时间
	CreatedBy int64          `gorm:"column:created_by" json:"created_by"`                             // 创建者ID
	UpdatedBy int64          `gorm:"column:updated_by" json:"updated_by"`                             // 更新者ID
	DeletedBy int64          `gorm:"column:deleted_by" json:"deleted_by"`                             // 删除者ID
	Remark    string         `gorm:"column:remark" json:"remark"`                                     // 备注
	Status    string         `gorm:"column:status;default:ON" json:"status"`                          // 菜单状态
	Type      string         `gorm:"column:type;default:MENU" json:"type"`                            // 菜单类型 FOLDER: 目录 MENU: 菜单 BUTTON: 按钮 EMBEDDED: 内嵌 LINK: 外链
	Path      string         `gorm:"column:path;default:''::character varying" json:"path"`           // 路径,当其类型为'按钮'的时候对应的数据操作名,例如:/user.service.v1.UserService/Login
	Redirect  string         `gorm:"column:redirect" json:"redirect"`                                 // 重定向地址
	Alias     string         `gorm:"column:alias" json:"alias"`                                       // 路由别名
	Name      string         `gorm:"column:name" json:"name"`                                         // 路由命名，然后我们可以使用 name 而不是 path 来传递 to 属性给 <router-link>。
	Component string         `gorm:"column:component;default:''::character varying" json:"component"` // 前端页面组件
	Meta      string         `gorm:"column:meta" json:"meta"`                                         // 前端页面组件
	ParentID  int64          `gorm:"column:parent_id" json:"parent_id"`                               // 父节点ID
}

// TableName SysMenu's table name
func (*SysMenu) TableName() string {
	return TableNameSysMenu
}
