// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysRoleDept = "sys_role_dept"

// SysRoleDept mapped from table <sys_role_dept>
type SysRoleDept struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // id
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`               // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`               // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`               // 删除时间
	CreatedBy int64          `gorm:"column:created_by" json:"created_by"`               // 创建者ID
	UpdatedBy int64          `gorm:"column:updated_by" json:"updated_by"`               // 更新者ID
	DeletedBy int64          `gorm:"column:deleted_by" json:"deleted_by"`               // 删除者ID
	RoleID    int64          `gorm:"column:role_id;not null" json:"role_id"`            // 角色ID
	DeptID    int64          `gorm:"column:dept_id;not null" json:"dept_id"`            // 部门ID
}

// TableName SysRoleDept's table name
func (*SysRoleDept) TableName() string {
	return TableNameSysRoleDept
}
