// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysAdminLoginRestriction = "sys_admin_login_restrictions"

// SysAdminLoginRestriction mapped from table <sys_admin_login_restrictions>
type SysAdminLoginRestriction struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // id
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`               // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`               // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`               // 删除时间
	CreatedBy int64          `gorm:"column:created_by" json:"created_by"`               // 创建者ID
	UpdatedBy int64          `gorm:"column:updated_by" json:"updated_by"`               // 更新者ID
	DeletedBy int64          `gorm:"column:deleted_by" json:"deleted_by"`               // 删除者ID
	TargetID  int64          `gorm:"column:target_id" json:"target_id"`                 // 目标用户ID
	Value     string         `gorm:"column:value" json:"value"`                         // 限制值（如IP地址、MAC地址或地区代码）
	Reason    string         `gorm:"column:reason" json:"reason"`                       // 限制原因
	Type      string         `gorm:"column:type;default:BLACKLIST" json:"type"`         // 限制类型
	Method    string         `gorm:"column:method;default:IP" json:"method"`            // 限制方式
}

// TableName SysAdminLoginRestriction's table name
func (*SysAdminLoginRestriction) TableName() string {
	return TableNameSysAdminLoginRestriction
}
