// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysTask = "sys_tasks"

// SysTask mapped from table <sys_tasks>
type SysTask struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // id
	CreatedAt   time.Time      `gorm:"column:created_at" json:"created_at"`               // 创建时间
	UpdatedAt   time.Time      `gorm:"column:updated_at" json:"updated_at"`               // 更新时间
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`               // 删除时间
	CreatedBy   int64          `gorm:"column:created_by" json:"created_by"`               // 创建者ID
	UpdatedBy   int64          `gorm:"column:updated_by" json:"updated_by"`               // 更新者ID
	DeletedBy   int64          `gorm:"column:deleted_by" json:"deleted_by"`               // 删除者ID
	Remark      string         `gorm:"column:remark" json:"remark"`                       // 备注
	TenantID    int64          `gorm:"column:tenant_id" json:"tenant_id"`                 // 租户ID
	Type        string         `gorm:"column:type;default:PERIODIC" json:"type"`          // 任务类型
	TypeName    string         `gorm:"column:type_name" json:"type_name"`                 // 任务执行类型名
	TaskPayload string         `gorm:"column:task_payload" json:"task_payload"`           // 任务数据
	CronSpec    string         `gorm:"column:cron_spec" json:"cron_spec"`                 // cron表达式
	TaskOptions string         `gorm:"column:task_options" json:"task_options"`           // 任务选项
	Enable      bool           `gorm:"column:enable" json:"enable"`                       // 启用/禁用任务
}

// TableName SysTask's table name
func (*SysTask) TableName() string {
	return TableNameSysTask
}
