// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysRole = "sys_roles"

// SysRole mapped from table <sys_roles>
type SysRole struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // id
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`               // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`               // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`               // 删除时间
	CreatedBy int64          `gorm:"column:created_by" json:"created_by"`               // 创建者ID
	UpdatedBy int64          `gorm:"column:updated_by" json:"updated_by"`               // 更新者ID
	DeletedBy int64          `gorm:"column:deleted_by" json:"deleted_by"`               // 删除者ID
	Remark    string         `gorm:"column:remark" json:"remark"`                       // 备注
	SortOrder int32          `gorm:"column:sort_order" json:"sort_order"`               // 排序顺序，值越小越靠前
	TenantID  int64          `gorm:"column:tenant_id" json:"tenant_id"`                 // 租户ID
	Name      string         `gorm:"column:name" json:"name"`                           // 角色名称
	Code      string         `gorm:"column:code" json:"code"`                           // 角色标识
	Menus     string         `gorm:"column:menus" json:"menus"`                         // 分配的菜单列表
	Apis      string         `gorm:"column:apis" json:"apis"`                           // 分配的API列表
	DataScope string         `gorm:"column:data_scope" json:"data_scope"`               // 数据权限范围
	Status    string         `gorm:"column:status;default:ON" json:"status"`            // 角色状态
	ParentID  int64          `gorm:"column:parent_id" json:"parent_id"`                 // 父节点ID
}

// TableName SysRole's table name
func (*SysRole) TableName() string {
	return TableNameSysRole
}
