// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysAdminLoginLog = "sys_admin_login_logs"

// SysAdminLoginLog mapped from table <sys_admin_login_logs>
type SysAdminLoginLog struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // id
	CreatedAt      time.Time `gorm:"column:created_at" json:"created_at"`               // 创建时间
	LoginIP        string    `gorm:"column:login_ip" json:"login_ip"`                   // 登录IP地址
	LoginMac       string    `gorm:"column:login_mac" json:"login_mac"`                 // 登录MAC地址
	LoginTime      time.Time `gorm:"column:login_time" json:"login_time"`               // 登录时间
	UserAgent      string    `gorm:"column:user_agent" json:"user_agent"`               // 浏览器的用户代理信息
	BrowserName    string    `gorm:"column:browser_name" json:"browser_name"`           // 浏览器名称
	BrowserVersion string    `gorm:"column:browser_version" json:"browser_version"`     // 浏览器版本
	ClientID       string    `gorm:"column:client_id" json:"client_id"`                 // 客户端ID
	ClientName     string    `gorm:"column:client_name" json:"client_name"`             // 客户端名称
	OsName         string    `gorm:"column:os_name" json:"os_name"`                     // 操作系统名称
	OsVersion      string    `gorm:"column:os_version" json:"os_version"`               // 操作系统版本
	UserID         int64     `gorm:"column:user_id" json:"user_id"`                     // 操作者用户ID
	Username       string    `gorm:"column:username" json:"username"`                   // 操作者账号名
	StatusCode     int32     `gorm:"column:status_code" json:"status_code"`             // 状态码
	Success        bool      `gorm:"column:success" json:"success"`                     // 操作成功
	Reason         string    `gorm:"column:reason" json:"reason"`                       // 登录失败原因
	Location       string    `gorm:"column:location" json:"location"`                   // 登录地理位置
}

// TableName SysAdminLoginLog's table name
func (*SysAdminLoginLog) TableName() string {
	return TableNameSysAdminLoginLog
}
