// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysDepartment = "sys_departments"

// SysDepartment mapped from table <sys_departments>
type SysDepartment struct {
	ID             int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`      // id
	CreatedAt      time.Time      `gorm:"column:created_at" json:"created_at"`                    // 创建时间
	UpdatedAt      time.Time      `gorm:"column:updated_at" json:"updated_at"`                    // 更新时间
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`                    // 删除时间
	CreatedBy      int64          `gorm:"column:created_by" json:"created_by"`                    // 创建者ID
	UpdatedBy      int64          `gorm:"column:updated_by" json:"updated_by"`                    // 更新者ID
	DeletedBy      int64          `gorm:"column:deleted_by" json:"deleted_by"`                    // 删除者ID
	SortOrder      int32          `gorm:"column:sort_order" json:"sort_order"`                    // 排序顺序，值越小越靠前
	Remark         string         `gorm:"column:remark" json:"remark"`                            // 备注
	TenantID       int64          `gorm:"column:tenant_id" json:"tenant_id"`                      // 租户ID
	Name           string         `gorm:"column:name" json:"name"`                                // 部门名称
	OrganizationID int64          `gorm:"column:organization_id;not null" json:"organization_id"` // 所属组织ID
	ManagerID      int64          `gorm:"column:manager_id" json:"manager_id"`                    // 负责人ID
	Status         string         `gorm:"column:status;default:ON" json:"status"`                 // 部门状态
	Description    string         `gorm:"column:description" json:"description"`                  // 职能描述
	ParentID       int64          `gorm:"column:parent_id" json:"parent_id"`                      // 父节点ID
}

// TableName SysDepartment's table name
func (*SysDepartment) TableName() string {
	return TableNameSysDepartment
}
