// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysUserPosition = "sys_user_position"

// SysUserPosition mapped from table <sys_user_position>
type SysUserPosition struct {
	ID         int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // id
	CreatedAt  time.Time      `gorm:"column:created_at" json:"created_at"`               // 创建时间
	UpdatedAt  time.Time      `gorm:"column:updated_at" json:"updated_at"`               // 更新时间
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`               // 删除时间
	CreatedBy  int64          `gorm:"column:created_by" json:"created_by"`               // 创建者ID
	UpdatedBy  int64          `gorm:"column:updated_by" json:"updated_by"`               // 更新者ID
	DeletedBy  int64          `gorm:"column:deleted_by" json:"deleted_by"`               // 删除者ID
	UserID     int64          `gorm:"column:user_id;not null" json:"user_id"`            // 用户ID
	PositionID int64          `gorm:"column:position_id;not null" json:"position_id"`    // 职位ID
}

// TableName SysUserPosition's table name
func (*SysUserPosition) TableName() string {
	return TableNameSysUserPosition
}
