// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysAdminOperationLog = "sys_admin_operation_logs"

// SysAdminOperationLog mapped from table <sys_admin_operation_logs>
type SysAdminOperationLog struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // id
	CreatedAt      time.Time `gorm:"column:created_at" json:"created_at"`               // 创建时间
	RequestID      string    `gorm:"column:request_id" json:"request_id"`               // 请求ID
	Method         string    `gorm:"column:method" json:"method"`                       // 请求方法
	Operation      string    `gorm:"column:operation" json:"operation"`                 // 操作方法
	Path           string    `gorm:"column:path" json:"path"`                           // 请求路径
	Referer        string    `gorm:"column:referer" json:"referer"`                     // 请求源
	RequestURI     string    `gorm:"column:request_uri" json:"request_uri"`             // 请求URI
	RequestBody    string    `gorm:"column:request_body" json:"request_body"`           // 请求体
	RequestHeader  string    `gorm:"column:request_header" json:"request_header"`       // 请求头
	Response       string    `gorm:"column:response" json:"response"`                   // 响应信息
	CostTime       float64   `gorm:"column:cost_time" json:"cost_time"`                 // 操作耗时
	UserID         int64     `gorm:"column:user_id" json:"user_id"`                     // 操作者用户ID
	Username       string    `gorm:"column:username" json:"username"`                   // 操作者账号名
	ClientIP       string    `gorm:"column:client_ip" json:"client_ip"`                 // 操作者IP
	StatusCode     int32     `gorm:"column:status_code" json:"status_code"`             // 状态码
	Reason         string    `gorm:"column:reason" json:"reason"`                       // 操作失败原因
	Success        bool      `gorm:"column:success" json:"success"`                     // 操作成功
	Location       string    `gorm:"column:location" json:"location"`                   // 操作地理位置
	UserAgent      string    `gorm:"column:user_agent" json:"user_agent"`               // 浏览器的用户代理信息
	BrowserName    string    `gorm:"column:browser_name" json:"browser_name"`           // 浏览器名称
	BrowserVersion string    `gorm:"column:browser_version" json:"browser_version"`     // 浏览器版本
	ClientID       string    `gorm:"column:client_id" json:"client_id"`                 // 客户端ID
	ClientName     string    `gorm:"column:client_name" json:"client_name"`             // 客户端名称
	OsName         string    `gorm:"column:os_name" json:"os_name"`                     // 操作系统名称
	OsVersion      string    `gorm:"column:os_version" json:"os_version"`               // 操作系统版本
}

// TableName SysAdminOperationLog's table name
func (*SysAdminOperationLog) TableName() string {
	return TableNameSysAdminOperationLog
}
