// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysLanguage = "sys_languages"

// SysLanguage mapped from table <sys_languages>
type SysLanguage struct {
	ID           int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // id
	CreatedAt    time.Time      `gorm:"column:created_at" json:"created_at"`               // 创建时间
	UpdatedAt    time.Time      `gorm:"column:updated_at" json:"updated_at"`               // 更新时间
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`               // 删除时间
	CreatedBy    int64          `gorm:"column:created_by" json:"created_by"`               // 创建者ID
	UpdatedBy    int64          `gorm:"column:updated_by" json:"updated_by"`               // 更新者ID
	DeletedBy    int64          `gorm:"column:deleted_by" json:"deleted_by"`               // 删除者ID
	SortOrder    int32          `gorm:"column:sort_order" json:"sort_order"`               // 排序顺序，值越小越靠前
	IsEnabled    bool           `gorm:"column:is_enabled;default:true" json:"is_enabled"`  // 是否启用
	LanguageCode string         `gorm:"column:language_code" json:"language_code"`         // 标准语言代码
	LanguageName string         `gorm:"column:language_name" json:"language_name"`         // 语言名称
	NativeName   string         `gorm:"column:native_name" json:"native_name"`             // 本地语言名称
	IsDefault    bool           `gorm:"column:is_default" json:"is_default"`               // 是否为默认语言
}

// TableName SysLanguage's table name
func (*SysLanguage) TableName() string {
	return TableNameSysLanguage
}
