// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysTenant = "sys_tenants"

// SysTenant mapped from table <sys_tenants>
type SysTenant struct {
	ID               int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // id
	CreatedAt        time.Time      `gorm:"column:created_at" json:"created_at"`               // 创建时间
	UpdatedAt        time.Time      `gorm:"column:updated_at" json:"updated_at"`               // 更新时间
	DeletedAt        gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`               // 删除时间
	CreatedBy        int64          `gorm:"column:created_by" json:"created_by"`               // 创建者ID
	UpdatedBy        int64          `gorm:"column:updated_by" json:"updated_by"`               // 更新者ID
	DeletedBy        int64          `gorm:"column:deleted_by" json:"deleted_by"`               // 删除者ID
	Remark           string         `gorm:"column:remark" json:"remark"`                       // 备注
	Name             string         `gorm:"column:name" json:"name"`                           // 租户名称
	Code             string         `gorm:"column:code" json:"code"`                           // 租户编号
	LogoURL          string         `gorm:"column:logo_url" json:"logo_url"`                   // 租户logo地址
	Industry         string         `gorm:"column:industry" json:"industry"`                   // 所属行业
	AdminUserID      int64          `gorm:"column:admin_user_id" json:"admin_user_id"`         // 管理员用户ID
	Status           string         `gorm:"column:status;default:ON" json:"status"`            // 租户状态
	Type             string         `gorm:"column:type;default:PAID" json:"type"`              // 租户类型
	AuditStatus      string         `gorm:"column:audit_status" json:"audit_status"`           // 审核状态
	SubscriptionAt   time.Time      `gorm:"column:subscription_at" json:"subscription_at"`     // 订阅时间
	UnsubscribeAt    time.Time      `gorm:"column:unsubscribe_at" json:"unsubscribe_at"`       // 取消订阅时间
	SubscriptionPlan string         `gorm:"column:subscription_plan" json:"subscription_plan"` // 订阅套餐
	ExpiredAt        time.Time      `gorm:"column:expired_at" json:"expired_at"`               // 租户有效期
	LastLoginTime    time.Time      `gorm:"column:last_login_time" json:"last_login_time"`     // 最后一次登录的时间
	LastLoginIP      string         `gorm:"column:last_login_ip" json:"last_login_ip"`         // 最后一次登录的IP
}

// TableName SysTenant's table name
func (*SysTenant) TableName() string {
	return TableNameSysTenant
}
