// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysUser = "sys_users"

// SysUser mapped from table <sys_users>
type SysUser struct {
	ID            int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                // id
	CreatedBy     int64          `gorm:"column:created_by" json:"created_by"`                              // 创建者ID
	UpdatedBy     int64          `gorm:"column:updated_by" json:"updated_by"`                              // 更新者ID
	DeletedBy     int64          `gorm:"column:deleted_by" json:"deleted_by"`                              // 删除者ID
	CreatedAt     time.Time      `gorm:"column:created_at" json:"created_at"`                              // 创建时间
	UpdatedAt     time.Time      `gorm:"column:updated_at" json:"updated_at"`                              // 更新时间
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`                              // 删除时间
	Remark        string         `gorm:"column:remark" json:"remark"`                                      // 备注
	TenantID      int64          `gorm:"column:tenant_id" json:"tenant_id"`                                // 租户ID
	Username      string         `gorm:"column:username" json:"username"`                                  // 用户名
	Nickname      string         `gorm:"column:nickname" json:"nickname"`                                  // 昵称
	Realname      string         `gorm:"column:realname" json:"realname"`                                  // 真实名字
	Email         string         `gorm:"column:email" json:"email"`                                        // 电子邮箱
	Mobile        string         `gorm:"column:mobile;default:''::character varying" json:"mobile"`        // 手机号码
	Telephone     string         `gorm:"column:telephone;default:''::character varying" json:"telephone"`  // 座机号码
	Avatar        string         `gorm:"column:avatar" json:"avatar"`                                      // 头像
	Address       string         `gorm:"column:address;default:''::character varying" json:"address"`      // 地址
	Region        string         `gorm:"column:region;default:''::character varying" json:"region"`        // 国家地区
	Description   string         `gorm:"column:description" json:"description"`                            // 个人说明
	Gender        string         `gorm:"column:gender;default:SECRET" json:"gender"`                       // 性别
	Authority     string         `gorm:"column:authority;not null;default:CUSTOMER_USER" json:"authority"` // 授权
	Status        string         `gorm:"column:status;default:ON" json:"status"`                           // 用户状态
	LastLoginTime time.Time      `gorm:"column:last_login_time" json:"last_login_time"`                    // 最后一次登录的时间
	LastLoginIP   string         `gorm:"column:last_login_ip" json:"last_login_ip"`                        // 最后一次登录的IP
	OrgID         int64          `gorm:"column:org_id" json:"org_id"`                                      // 组织ID
	DepartmentID  int64          `gorm:"column:department_id" json:"department_id"`                        // 部门ID
	PositionID    int64          `gorm:"column:position_id" json:"position_id"`                            // 职位ID
	WorkID        int64          `gorm:"column:work_id" json:"work_id"`                                    // 员工工号
	RoleIds       string         `gorm:"column:role_ids" json:"role_ids"`                                  // 角色ID列表
}

// TableName SysUser's table name
func (*SysUser) TableName() string {
	return TableNameSysUser
}
