// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysDictType = "sys_dict_types"

// SysDictType mapped from table <sys_dict_types>
type SysDictType struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // id
	CreatedAt   time.Time      `gorm:"column:created_at" json:"created_at"`               // 创建时间
	UpdatedAt   time.Time      `gorm:"column:updated_at" json:"updated_at"`               // 更新时间
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`               // 删除时间
	CreatedBy   int64          `gorm:"column:created_by" json:"created_by"`               // 创建者ID
	UpdatedBy   int64          `gorm:"column:updated_by" json:"updated_by"`               // 更新者ID
	DeletedBy   int64          `gorm:"column:deleted_by" json:"deleted_by"`               // 删除者ID
	IsEnabled   bool           `gorm:"column:is_enabled;default:true" json:"is_enabled"`  // 是否启用
	SortOrder   int32          `gorm:"column:sort_order" json:"sort_order"`               // 排序顺序，值越小越靠前
	Description string         `gorm:"column:description" json:"description"`             // 描述
	TenantID    int64          `gorm:"column:tenant_id" json:"tenant_id"`                 // 租户ID
	TypeCode    string         `gorm:"column:type_code" json:"type_code"`                 // 字典类型唯一代码
	TypeName    string         `gorm:"column:type_name" json:"type_name"`                 // 字典类型名称
}

// TableName SysDictType's table name
func (*SysDictType) TableName() string {
	return TableNameSysDictType
}
