// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysOrganization = "sys_organizations"

// SysOrganization mapped from table <sys_organizations>
type SysOrganization struct {
	ID               int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // id
	CreatedAt        time.Time      `gorm:"column:created_at" json:"created_at"`               // 创建时间
	UpdatedAt        time.Time      `gorm:"column:updated_at" json:"updated_at"`               // 更新时间
	DeletedAt        gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`               // 删除时间
	CreatedBy        int64          `gorm:"column:created_by" json:"created_by"`               // 创建者ID
	UpdatedBy        int64          `gorm:"column:updated_by" json:"updated_by"`               // 更新者ID
	DeletedBy        int64          `gorm:"column:deleted_by" json:"deleted_by"`               // 删除者ID
	Remark           string         `gorm:"column:remark" json:"remark"`                       // 备注
	SortOrder        int32          `gorm:"column:sort_order" json:"sort_order"`               // 排序顺序，值越小越靠前
	TenantID         int64          `gorm:"column:tenant_id" json:"tenant_id"`                 // 租户ID
	Name             string         `gorm:"column:name" json:"name"`                           // 组织名称
	Status           string         `gorm:"column:status;default:ON" json:"status"`            // 组织状态
	OrganizationType string         `gorm:"column:organization_type" json:"organization_type"` // 组织类型
	CreditCode       string         `gorm:"column:credit_code" json:"credit_code"`             // 统一社会信用代码
	Address          string         `gorm:"column:address" json:"address"`                     // 注册地址
	BusinessScope    string         `gorm:"column:business_scope" json:"business_scope"`       // 核心业务范围
	IsLegalEntity    bool           `gorm:"column:is_legal_entity" json:"is_legal_entity"`     // 是否法人实体
	ManagerID        int64          `gorm:"column:manager_id" json:"manager_id"`               // 负责人ID
	ParentID         int64          `gorm:"column:parent_id" json:"parent_id"`                 // 父节点ID
}

// TableName SysOrganization's table name
func (*SysOrganization) TableName() string {
	return TableNameSysOrganization
}
