// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysUserCredential = "sys_user_credentials"

// SysUserCredential mapped from table <sys_user_credentials>
type SysUserCredential struct {
	ID                     int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                   // id
	CreatedAt              time.Time      `gorm:"column:created_at" json:"created_at"`                                 // 创建时间
	UpdatedAt              time.Time      `gorm:"column:updated_at" json:"updated_at"`                                 // 更新时间
	DeletedAt              gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`                                 // 删除时间
	TenantID               int64          `gorm:"column:tenant_id" json:"tenant_id"`                                   // 租户ID
	UserID                 int64          `gorm:"column:user_id" json:"user_id"`                                       // 关联主表的用户ID
	IdentityType           string         `gorm:"column:identity_type;default:USERNAME" json:"identity_type"`          // 认证方式类型
	Identifier             string         `gorm:"column:identifier" json:"identifier"`                                 // 身份唯一标识符
	CredentialType         string         `gorm:"column:credential_type;default:PASSWORD_HASH" json:"credential_type"` // 凭证类型
	Credential             string         `gorm:"column:credential" json:"credential"`                                 // 凭证
	IsPrimary              bool           `gorm:"column:is_primary" json:"is_primary"`                                 // 是否主认证方式
	Status                 string         `gorm:"column:status;default:ENABLED" json:"status"`                         // 凭证状态
	ExtraInfo              string         `gorm:"column:extra_info" json:"extra_info"`                                 // 扩展信息
	Provider               string         `gorm:"column:provider" json:"provider"`                                     // 第三方平台标识
	ProviderAccountID      string         `gorm:"column:provider_account_id" json:"provider_account_id"`               // 第三方平台的账号唯一ID
	ActivateTokenHash      string         `gorm:"column:activate_token_hash" json:"activate_token_hash"`               // 激活令牌哈希（不要存明文）
	ActivateTokenExpiresAt time.Time      `gorm:"column:activate_token_expires_at" json:"activate_token_expires_at"`   // 激活令牌到期时间
	ActivateTokenUsedAt    time.Time      `gorm:"column:activate_token_used_at" json:"activate_token_used_at"`         // 激活令牌使用时间，单次使用时记录
	ResetTokenHash         string         `gorm:"column:reset_token_hash" json:"reset_token_hash"`                     // 重置密码令牌哈希（不要存明文）
	ResetTokenExpiresAt    time.Time      `gorm:"column:reset_token_expires_at" json:"reset_token_expires_at"`         // 重置令牌到期时间
	ResetTokenUsedAt       time.Time      `gorm:"column:reset_token_used_at" json:"reset_token_used_at"`               // 重置令牌使用时间
}

// TableName SysUserCredential's table name
func (*SysUserCredential) TableName() string {
	return TableNameSysUserCredential
}
