// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysAPIResource = "sys_api_resources"

// SysAPIResource mapped from table <sys_api_resources>
type SysAPIResource struct {
	ID                int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`   // id
	CreatedAt         time.Time      `gorm:"column:created_at" json:"created_at"`                 // 创建时间
	UpdatedAt         time.Time      `gorm:"column:updated_at" json:"updated_at"`                 // 更新时间
	DeletedAt         gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`                 // 删除时间
	CreatedBy         int64          `gorm:"column:created_by" json:"created_by"`                 // 创建者ID
	UpdatedBy         int64          `gorm:"column:updated_by" json:"updated_by"`                 // 更新者ID
	DeletedBy         int64          `gorm:"column:deleted_by" json:"deleted_by"`                 // 删除者ID
	Description       string         `gorm:"column:description" json:"description"`               // 描述
	Module            string         `gorm:"column:module" json:"module"`                         // 所属业务模块
	ModuleDescription string         `gorm:"column:module_description" json:"module_description"` // 业务模块描述
	Operation         string         `gorm:"column:operation" json:"operation"`                   // 接口操作名
	Path              string         `gorm:"column:path" json:"path"`                             // 接口路径
	Method            string         `gorm:"column:method" json:"method"`                         // 请求方法
	Scope             string         `gorm:"column:scope;default:ADMIN" json:"scope"`             // 作用域
}

// TableName SysAPIResource's table name
func (*SysAPIResource) TableName() string {
	return TableNameSysAPIResource
}

func (s *SysAPIResource) name() {

}
