// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"kratos-admin/app/admin/service/internal/data/gorm/model"
)

func newAdminOperationLog(db *gorm.DB, opts ...gen.DOOption) adminOperationLog {
	_adminOperationLog := adminOperationLog{}

	_adminOperationLog.adminOperationLogDo.UseDB(db, opts...)
	_adminOperationLog.adminOperationLogDo.UseModel(&model.AdminOperationLog{})

	tableName := _adminOperationLog.adminOperationLogDo.TableName()
	_adminOperationLog.ALL = field.NewAsterisk(tableName)
	_adminOperationLog.ID = field.NewInt32(tableName, "id")
	_adminOperationLog.CreatedAt = field.NewTime(tableName, "created_at")
	_adminOperationLog.RequestID = field.NewString(tableName, "request_id")
	_adminOperationLog.Method = field.NewString(tableName, "method")
	_adminOperationLog.Operation = field.NewString(tableName, "operation")
	_adminOperationLog.Path = field.NewString(tableName, "path")
	_adminOperationLog.Referer = field.NewString(tableName, "referer")
	_adminOperationLog.RequestURI = field.NewString(tableName, "request_uri")
	_adminOperationLog.RequestBody = field.NewString(tableName, "request_body")
	_adminOperationLog.RequestHeader = field.NewString(tableName, "request_header")
	_adminOperationLog.Response = field.NewString(tableName, "response")
	_adminOperationLog.CostTime = field.NewFloat64(tableName, "cost_time")
	_adminOperationLog.UserID = field.NewInt64(tableName, "user_id")
	_adminOperationLog.Username = field.NewString(tableName, "username")
	_adminOperationLog.ClientIP = field.NewString(tableName, "client_ip")
	_adminOperationLog.StatusCode = field.NewInt32(tableName, "status_code")
	_adminOperationLog.Reason = field.NewString(tableName, "reason")
	_adminOperationLog.Success = field.NewBool(tableName, "success")
	_adminOperationLog.Location = field.NewString(tableName, "location")
	_adminOperationLog.UserAgent = field.NewString(tableName, "user_agent")
	_adminOperationLog.BrowserName = field.NewString(tableName, "browser_name")
	_adminOperationLog.BrowserVersion = field.NewString(tableName, "browser_version")
	_adminOperationLog.ClientID = field.NewString(tableName, "client_id")
	_adminOperationLog.ClientName = field.NewString(tableName, "client_name")
	_adminOperationLog.OsName = field.NewString(tableName, "os_name")
	_adminOperationLog.OsVersion = field.NewString(tableName, "os_version")

	_adminOperationLog.fillFieldMap()

	return _adminOperationLog
}

type adminOperationLog struct {
	adminOperationLogDo adminOperationLogDo

	ALL            field.Asterisk
	ID             field.Int32   // id
	CreatedAt      field.Time    // 创建时间
	RequestID      field.String  // 请求ID
	Method         field.String  // 请求方法
	Operation      field.String  // 操作方法
	Path           field.String  // 请求路径
	Referer        field.String  // 请求源
	RequestURI     field.String  // 请求URI
	RequestBody    field.String  // 请求体
	RequestHeader  field.String  // 请求头
	Response       field.String  // 响应信息
	CostTime       field.Float64 // 操作耗时
	UserID         field.Int64   // 操作者用户ID
	Username       field.String  // 操作者账号名
	ClientIP       field.String  // 操作者IP
	StatusCode     field.Int32   // 状态码
	Reason         field.String  // 操作失败原因
	Success        field.Bool    // 操作成功
	Location       field.String  // 操作地理位置
	UserAgent      field.String  // 浏览器的用户代理信息
	BrowserName    field.String  // 浏览器名称
	BrowserVersion field.String  // 浏览器版本
	ClientID       field.String  // 客户端ID
	ClientName     field.String  // 客户端名称
	OsName         field.String  // 操作系统名称
	OsVersion      field.String  // 操作系统版本

	fieldMap map[string]field.Expr
}

func (a adminOperationLog) Table(newTableName string) *adminOperationLog {
	a.adminOperationLogDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a adminOperationLog) As(alias string) *adminOperationLog {
	a.adminOperationLogDo.DO = *(a.adminOperationLogDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *adminOperationLog) updateTableName(table string) *adminOperationLog {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt32(table, "id")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.RequestID = field.NewString(table, "request_id")
	a.Method = field.NewString(table, "method")
	a.Operation = field.NewString(table, "operation")
	a.Path = field.NewString(table, "path")
	a.Referer = field.NewString(table, "referer")
	a.RequestURI = field.NewString(table, "request_uri")
	a.RequestBody = field.NewString(table, "request_body")
	a.RequestHeader = field.NewString(table, "request_header")
	a.Response = field.NewString(table, "response")
	a.CostTime = field.NewFloat64(table, "cost_time")
	a.UserID = field.NewInt64(table, "user_id")
	a.Username = field.NewString(table, "username")
	a.ClientIP = field.NewString(table, "client_ip")
	a.StatusCode = field.NewInt32(table, "status_code")
	a.Reason = field.NewString(table, "reason")
	a.Success = field.NewBool(table, "success")
	a.Location = field.NewString(table, "location")
	a.UserAgent = field.NewString(table, "user_agent")
	a.BrowserName = field.NewString(table, "browser_name")
	a.BrowserVersion = field.NewString(table, "browser_version")
	a.ClientID = field.NewString(table, "client_id")
	a.ClientName = field.NewString(table, "client_name")
	a.OsName = field.NewString(table, "os_name")
	a.OsVersion = field.NewString(table, "os_version")

	a.fillFieldMap()

	return a
}

func (a *adminOperationLog) WithContext(ctx context.Context) IAdminOperationLogDo {
	return a.adminOperationLogDo.WithContext(ctx)
}

func (a adminOperationLog) TableName() string { return a.adminOperationLogDo.TableName() }

func (a adminOperationLog) Alias() string { return a.adminOperationLogDo.Alias() }

func (a adminOperationLog) Columns(cols ...field.Expr) gen.Columns {
	return a.adminOperationLogDo.Columns(cols...)
}

func (a *adminOperationLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *adminOperationLog) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 26)
	a.fieldMap["id"] = a.ID
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["request_id"] = a.RequestID
	a.fieldMap["method"] = a.Method
	a.fieldMap["operation"] = a.Operation
	a.fieldMap["path"] = a.Path
	a.fieldMap["referer"] = a.Referer
	a.fieldMap["request_uri"] = a.RequestURI
	a.fieldMap["request_body"] = a.RequestBody
	a.fieldMap["request_header"] = a.RequestHeader
	a.fieldMap["response"] = a.Response
	a.fieldMap["cost_time"] = a.CostTime
	a.fieldMap["user_id"] = a.UserID
	a.fieldMap["username"] = a.Username
	a.fieldMap["client_ip"] = a.ClientIP
	a.fieldMap["status_code"] = a.StatusCode
	a.fieldMap["reason"] = a.Reason
	a.fieldMap["success"] = a.Success
	a.fieldMap["location"] = a.Location
	a.fieldMap["user_agent"] = a.UserAgent
	a.fieldMap["browser_name"] = a.BrowserName
	a.fieldMap["browser_version"] = a.BrowserVersion
	a.fieldMap["client_id"] = a.ClientID
	a.fieldMap["client_name"] = a.ClientName
	a.fieldMap["os_name"] = a.OsName
	a.fieldMap["os_version"] = a.OsVersion
}

func (a adminOperationLog) clone(db *gorm.DB) adminOperationLog {
	a.adminOperationLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a adminOperationLog) replaceDB(db *gorm.DB) adminOperationLog {
	a.adminOperationLogDo.ReplaceDB(db)
	return a
}

type adminOperationLogDo struct{ gen.DO }

type IAdminOperationLogDo interface {
	gen.SubQuery
	Debug() IAdminOperationLogDo
	WithContext(ctx context.Context) IAdminOperationLogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAdminOperationLogDo
	WriteDB() IAdminOperationLogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAdminOperationLogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAdminOperationLogDo
	Not(conds ...gen.Condition) IAdminOperationLogDo
	Or(conds ...gen.Condition) IAdminOperationLogDo
	Select(conds ...field.Expr) IAdminOperationLogDo
	Where(conds ...gen.Condition) IAdminOperationLogDo
	Order(conds ...field.Expr) IAdminOperationLogDo
	Distinct(cols ...field.Expr) IAdminOperationLogDo
	Omit(cols ...field.Expr) IAdminOperationLogDo
	Join(table schema.Tabler, on ...field.Expr) IAdminOperationLogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAdminOperationLogDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAdminOperationLogDo
	Group(cols ...field.Expr) IAdminOperationLogDo
	Having(conds ...gen.Condition) IAdminOperationLogDo
	Limit(limit int) IAdminOperationLogDo
	Offset(offset int) IAdminOperationLogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAdminOperationLogDo
	Unscoped() IAdminOperationLogDo
	Create(values ...*model.AdminOperationLog) error
	CreateInBatches(values []*model.AdminOperationLog, batchSize int) error
	Save(values ...*model.AdminOperationLog) error
	First() (*model.AdminOperationLog, error)
	Take() (*model.AdminOperationLog, error)
	Last() (*model.AdminOperationLog, error)
	Find() ([]*model.AdminOperationLog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AdminOperationLog, err error)
	FindInBatches(result *[]*model.AdminOperationLog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AdminOperationLog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAdminOperationLogDo
	Assign(attrs ...field.AssignExpr) IAdminOperationLogDo
	Joins(fields ...field.RelationField) IAdminOperationLogDo
	Preload(fields ...field.RelationField) IAdminOperationLogDo
	FirstOrInit() (*model.AdminOperationLog, error)
	FirstOrCreate() (*model.AdminOperationLog, error)
	FindByPage(offset int, limit int) (result []*model.AdminOperationLog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAdminOperationLogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a adminOperationLogDo) Debug() IAdminOperationLogDo {
	return a.withDO(a.DO.Debug())
}

func (a adminOperationLogDo) WithContext(ctx context.Context) IAdminOperationLogDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a adminOperationLogDo) ReadDB() IAdminOperationLogDo {
	return a.Clauses(dbresolver.Read)
}

func (a adminOperationLogDo) WriteDB() IAdminOperationLogDo {
	return a.Clauses(dbresolver.Write)
}

func (a adminOperationLogDo) Session(config *gorm.Session) IAdminOperationLogDo {
	return a.withDO(a.DO.Session(config))
}

func (a adminOperationLogDo) Clauses(conds ...clause.Expression) IAdminOperationLogDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a adminOperationLogDo) Returning(value interface{}, columns ...string) IAdminOperationLogDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a adminOperationLogDo) Not(conds ...gen.Condition) IAdminOperationLogDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a adminOperationLogDo) Or(conds ...gen.Condition) IAdminOperationLogDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a adminOperationLogDo) Select(conds ...field.Expr) IAdminOperationLogDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a adminOperationLogDo) Where(conds ...gen.Condition) IAdminOperationLogDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a adminOperationLogDo) Order(conds ...field.Expr) IAdminOperationLogDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a adminOperationLogDo) Distinct(cols ...field.Expr) IAdminOperationLogDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a adminOperationLogDo) Omit(cols ...field.Expr) IAdminOperationLogDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a adminOperationLogDo) Join(table schema.Tabler, on ...field.Expr) IAdminOperationLogDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a adminOperationLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAdminOperationLogDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a adminOperationLogDo) RightJoin(table schema.Tabler, on ...field.Expr) IAdminOperationLogDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a adminOperationLogDo) Group(cols ...field.Expr) IAdminOperationLogDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a adminOperationLogDo) Having(conds ...gen.Condition) IAdminOperationLogDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a adminOperationLogDo) Limit(limit int) IAdminOperationLogDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a adminOperationLogDo) Offset(offset int) IAdminOperationLogDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a adminOperationLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAdminOperationLogDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a adminOperationLogDo) Unscoped() IAdminOperationLogDo {
	return a.withDO(a.DO.Unscoped())
}

func (a adminOperationLogDo) Create(values ...*model.AdminOperationLog) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a adminOperationLogDo) CreateInBatches(values []*model.AdminOperationLog, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a adminOperationLogDo) Save(values ...*model.AdminOperationLog) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a adminOperationLogDo) First() (*model.AdminOperationLog, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminOperationLog), nil
	}
}

func (a adminOperationLogDo) Take() (*model.AdminOperationLog, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminOperationLog), nil
	}
}

func (a adminOperationLogDo) Last() (*model.AdminOperationLog, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminOperationLog), nil
	}
}

func (a adminOperationLogDo) Find() ([]*model.AdminOperationLog, error) {
	result, err := a.DO.Find()
	return result.([]*model.AdminOperationLog), err
}

func (a adminOperationLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AdminOperationLog, err error) {
	buf := make([]*model.AdminOperationLog, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a adminOperationLogDo) FindInBatches(result *[]*model.AdminOperationLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a adminOperationLogDo) Attrs(attrs ...field.AssignExpr) IAdminOperationLogDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a adminOperationLogDo) Assign(attrs ...field.AssignExpr) IAdminOperationLogDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a adminOperationLogDo) Joins(fields ...field.RelationField) IAdminOperationLogDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a adminOperationLogDo) Preload(fields ...field.RelationField) IAdminOperationLogDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a adminOperationLogDo) FirstOrInit() (*model.AdminOperationLog, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminOperationLog), nil
	}
}

func (a adminOperationLogDo) FirstOrCreate() (*model.AdminOperationLog, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminOperationLog), nil
	}
}

func (a adminOperationLogDo) FindByPage(offset int, limit int) (result []*model.AdminOperationLog, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a adminOperationLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a adminOperationLogDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a adminOperationLogDo) Delete(models ...*model.AdminOperationLog) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *adminOperationLogDo) withDO(do gen.Dao) *adminOperationLogDo {
	a.DO = *do.(*gen.DO)
	return a
}
