// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"kratos-admin/app/admin/service/internal/data/gorm/model"
)

func newAdminLoginRestriction(db *gorm.DB, opts ...gen.DOOption) adminLoginRestriction {
	_adminLoginRestriction := adminLoginRestriction{}

	_adminLoginRestriction.adminLoginRestrictionDo.UseDB(db, opts...)
	_adminLoginRestriction.adminLoginRestrictionDo.UseModel(&model.AdminLoginRestriction{})

	tableName := _adminLoginRestriction.adminLoginRestrictionDo.TableName()
	_adminLoginRestriction.ALL = field.NewAsterisk(tableName)
	_adminLoginRestriction.ID = field.NewInt32(tableName, "id")
	_adminLoginRestriction.CreatedAt = field.NewTime(tableName, "created_at")
	_adminLoginRestriction.UpdatedAt = field.NewTime(tableName, "updated_at")
	_adminLoginRestriction.DeletedAt = field.NewTime(tableName, "deleted_at")
	_adminLoginRestriction.CreateBy = field.NewInt64(tableName, "create_by")
	_adminLoginRestriction.UpdateBy = field.NewInt64(tableName, "update_by")
	_adminLoginRestriction.TargetID = field.NewInt64(tableName, "target_id")
	_adminLoginRestriction.Value = field.NewString(tableName, "value")
	_adminLoginRestriction.Reason = field.NewString(tableName, "reason")
	_adminLoginRestriction.Type = field.NewString(tableName, "type")
	_adminLoginRestriction.Method = field.NewString(tableName, "method")

	_adminLoginRestriction.fillFieldMap()

	return _adminLoginRestriction
}

type adminLoginRestriction struct {
	adminLoginRestrictionDo adminLoginRestrictionDo

	ALL       field.Asterisk
	ID        field.Int32  // id
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间
	DeletedAt field.Time   // 删除时间
	CreateBy  field.Int64  // 创建者ID
	UpdateBy  field.Int64  // 更新者ID
	TargetID  field.Int64  // 目标用户ID
	Value     field.String // 限制值（如IP地址、MAC地址或地区代码）
	Reason    field.String // 限制原因
	Type      field.String // 限制类型
	Method    field.String // 限制方式

	fieldMap map[string]field.Expr
}

func (a adminLoginRestriction) Table(newTableName string) *adminLoginRestriction {
	a.adminLoginRestrictionDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a adminLoginRestriction) As(alias string) *adminLoginRestriction {
	a.adminLoginRestrictionDo.DO = *(a.adminLoginRestrictionDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *adminLoginRestriction) updateTableName(table string) *adminLoginRestriction {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt32(table, "id")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.DeletedAt = field.NewTime(table, "deleted_at")
	a.CreateBy = field.NewInt64(table, "create_by")
	a.UpdateBy = field.NewInt64(table, "update_by")
	a.TargetID = field.NewInt64(table, "target_id")
	a.Value = field.NewString(table, "value")
	a.Reason = field.NewString(table, "reason")
	a.Type = field.NewString(table, "type")
	a.Method = field.NewString(table, "method")

	a.fillFieldMap()

	return a
}

func (a *adminLoginRestriction) WithContext(ctx context.Context) IAdminLoginRestrictionDo {
	return a.adminLoginRestrictionDo.WithContext(ctx)
}

func (a adminLoginRestriction) TableName() string { return a.adminLoginRestrictionDo.TableName() }

func (a adminLoginRestriction) Alias() string { return a.adminLoginRestrictionDo.Alias() }

func (a adminLoginRestriction) Columns(cols ...field.Expr) gen.Columns {
	return a.adminLoginRestrictionDo.Columns(cols...)
}

func (a *adminLoginRestriction) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *adminLoginRestriction) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 11)
	a.fieldMap["id"] = a.ID
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["deleted_at"] = a.DeletedAt
	a.fieldMap["create_by"] = a.CreateBy
	a.fieldMap["update_by"] = a.UpdateBy
	a.fieldMap["target_id"] = a.TargetID
	a.fieldMap["value"] = a.Value
	a.fieldMap["reason"] = a.Reason
	a.fieldMap["type"] = a.Type
	a.fieldMap["method"] = a.Method
}

func (a adminLoginRestriction) clone(db *gorm.DB) adminLoginRestriction {
	a.adminLoginRestrictionDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a adminLoginRestriction) replaceDB(db *gorm.DB) adminLoginRestriction {
	a.adminLoginRestrictionDo.ReplaceDB(db)
	return a
}

type adminLoginRestrictionDo struct{ gen.DO }

type IAdminLoginRestrictionDo interface {
	gen.SubQuery
	Debug() IAdminLoginRestrictionDo
	WithContext(ctx context.Context) IAdminLoginRestrictionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAdminLoginRestrictionDo
	WriteDB() IAdminLoginRestrictionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAdminLoginRestrictionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAdminLoginRestrictionDo
	Not(conds ...gen.Condition) IAdminLoginRestrictionDo
	Or(conds ...gen.Condition) IAdminLoginRestrictionDo
	Select(conds ...field.Expr) IAdminLoginRestrictionDo
	Where(conds ...gen.Condition) IAdminLoginRestrictionDo
	Order(conds ...field.Expr) IAdminLoginRestrictionDo
	Distinct(cols ...field.Expr) IAdminLoginRestrictionDo
	Omit(cols ...field.Expr) IAdminLoginRestrictionDo
	Join(table schema.Tabler, on ...field.Expr) IAdminLoginRestrictionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAdminLoginRestrictionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAdminLoginRestrictionDo
	Group(cols ...field.Expr) IAdminLoginRestrictionDo
	Having(conds ...gen.Condition) IAdminLoginRestrictionDo
	Limit(limit int) IAdminLoginRestrictionDo
	Offset(offset int) IAdminLoginRestrictionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAdminLoginRestrictionDo
	Unscoped() IAdminLoginRestrictionDo
	Create(values ...*model.AdminLoginRestriction) error
	CreateInBatches(values []*model.AdminLoginRestriction, batchSize int) error
	Save(values ...*model.AdminLoginRestriction) error
	First() (*model.AdminLoginRestriction, error)
	Take() (*model.AdminLoginRestriction, error)
	Last() (*model.AdminLoginRestriction, error)
	Find() ([]*model.AdminLoginRestriction, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AdminLoginRestriction, err error)
	FindInBatches(result *[]*model.AdminLoginRestriction, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AdminLoginRestriction) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAdminLoginRestrictionDo
	Assign(attrs ...field.AssignExpr) IAdminLoginRestrictionDo
	Joins(fields ...field.RelationField) IAdminLoginRestrictionDo
	Preload(fields ...field.RelationField) IAdminLoginRestrictionDo
	FirstOrInit() (*model.AdminLoginRestriction, error)
	FirstOrCreate() (*model.AdminLoginRestriction, error)
	FindByPage(offset int, limit int) (result []*model.AdminLoginRestriction, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAdminLoginRestrictionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a adminLoginRestrictionDo) Debug() IAdminLoginRestrictionDo {
	return a.withDO(a.DO.Debug())
}

func (a adminLoginRestrictionDo) WithContext(ctx context.Context) IAdminLoginRestrictionDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a adminLoginRestrictionDo) ReadDB() IAdminLoginRestrictionDo {
	return a.Clauses(dbresolver.Read)
}

func (a adminLoginRestrictionDo) WriteDB() IAdminLoginRestrictionDo {
	return a.Clauses(dbresolver.Write)
}

func (a adminLoginRestrictionDo) Session(config *gorm.Session) IAdminLoginRestrictionDo {
	return a.withDO(a.DO.Session(config))
}

func (a adminLoginRestrictionDo) Clauses(conds ...clause.Expression) IAdminLoginRestrictionDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a adminLoginRestrictionDo) Returning(value interface{}, columns ...string) IAdminLoginRestrictionDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a adminLoginRestrictionDo) Not(conds ...gen.Condition) IAdminLoginRestrictionDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a adminLoginRestrictionDo) Or(conds ...gen.Condition) IAdminLoginRestrictionDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a adminLoginRestrictionDo) Select(conds ...field.Expr) IAdminLoginRestrictionDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a adminLoginRestrictionDo) Where(conds ...gen.Condition) IAdminLoginRestrictionDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a adminLoginRestrictionDo) Order(conds ...field.Expr) IAdminLoginRestrictionDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a adminLoginRestrictionDo) Distinct(cols ...field.Expr) IAdminLoginRestrictionDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a adminLoginRestrictionDo) Omit(cols ...field.Expr) IAdminLoginRestrictionDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a adminLoginRestrictionDo) Join(table schema.Tabler, on ...field.Expr) IAdminLoginRestrictionDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a adminLoginRestrictionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAdminLoginRestrictionDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a adminLoginRestrictionDo) RightJoin(table schema.Tabler, on ...field.Expr) IAdminLoginRestrictionDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a adminLoginRestrictionDo) Group(cols ...field.Expr) IAdminLoginRestrictionDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a adminLoginRestrictionDo) Having(conds ...gen.Condition) IAdminLoginRestrictionDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a adminLoginRestrictionDo) Limit(limit int) IAdminLoginRestrictionDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a adminLoginRestrictionDo) Offset(offset int) IAdminLoginRestrictionDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a adminLoginRestrictionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAdminLoginRestrictionDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a adminLoginRestrictionDo) Unscoped() IAdminLoginRestrictionDo {
	return a.withDO(a.DO.Unscoped())
}

func (a adminLoginRestrictionDo) Create(values ...*model.AdminLoginRestriction) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a adminLoginRestrictionDo) CreateInBatches(values []*model.AdminLoginRestriction, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a adminLoginRestrictionDo) Save(values ...*model.AdminLoginRestriction) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a adminLoginRestrictionDo) First() (*model.AdminLoginRestriction, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminLoginRestriction), nil
	}
}

func (a adminLoginRestrictionDo) Take() (*model.AdminLoginRestriction, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminLoginRestriction), nil
	}
}

func (a adminLoginRestrictionDo) Last() (*model.AdminLoginRestriction, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminLoginRestriction), nil
	}
}

func (a adminLoginRestrictionDo) Find() ([]*model.AdminLoginRestriction, error) {
	result, err := a.DO.Find()
	return result.([]*model.AdminLoginRestriction), err
}

func (a adminLoginRestrictionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AdminLoginRestriction, err error) {
	buf := make([]*model.AdminLoginRestriction, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a adminLoginRestrictionDo) FindInBatches(result *[]*model.AdminLoginRestriction, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a adminLoginRestrictionDo) Attrs(attrs ...field.AssignExpr) IAdminLoginRestrictionDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a adminLoginRestrictionDo) Assign(attrs ...field.AssignExpr) IAdminLoginRestrictionDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a adminLoginRestrictionDo) Joins(fields ...field.RelationField) IAdminLoginRestrictionDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a adminLoginRestrictionDo) Preload(fields ...field.RelationField) IAdminLoginRestrictionDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a adminLoginRestrictionDo) FirstOrInit() (*model.AdminLoginRestriction, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminLoginRestriction), nil
	}
}

func (a adminLoginRestrictionDo) FirstOrCreate() (*model.AdminLoginRestriction, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminLoginRestriction), nil
	}
}

func (a adminLoginRestrictionDo) FindByPage(offset int, limit int) (result []*model.AdminLoginRestriction, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a adminLoginRestrictionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a adminLoginRestrictionDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a adminLoginRestrictionDo) Delete(models ...*model.AdminLoginRestriction) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *adminLoginRestrictionDo) withDO(do gen.Dao) *adminLoginRestrictionDo {
	a.DO = *do.(*gen.DO)
	return a
}
