// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"kratos-admin/app/admin/service/internal/data/gorm/model"
)

func newAdminLoginLog(db *gorm.DB, opts ...gen.DOOption) adminLoginLog {
	_adminLoginLog := adminLoginLog{}

	_adminLoginLog.adminLoginLogDo.UseDB(db, opts...)
	_adminLoginLog.adminLoginLogDo.UseModel(&model.AdminLoginLog{})

	tableName := _adminLoginLog.adminLoginLogDo.TableName()
	_adminLoginLog.ALL = field.NewAsterisk(tableName)
	_adminLoginLog.ID = field.NewInt32(tableName, "id")
	_adminLoginLog.CreatedAt = field.NewTime(tableName, "created_at")
	_adminLoginLog.LoginIP = field.NewString(tableName, "login_ip")
	_adminLoginLog.LoginMac = field.NewString(tableName, "login_mac")
	_adminLoginLog.LoginTime = field.NewTime(tableName, "login_time")
	_adminLoginLog.UserAgent = field.NewString(tableName, "user_agent")
	_adminLoginLog.BrowserName = field.NewString(tableName, "browser_name")
	_adminLoginLog.BrowserVersion = field.NewString(tableName, "browser_version")
	_adminLoginLog.ClientID = field.NewString(tableName, "client_id")
	_adminLoginLog.ClientName = field.NewString(tableName, "client_name")
	_adminLoginLog.OsName = field.NewString(tableName, "os_name")
	_adminLoginLog.OsVersion = field.NewString(tableName, "os_version")
	_adminLoginLog.UserID = field.NewInt64(tableName, "user_id")
	_adminLoginLog.Username = field.NewString(tableName, "username")
	_adminLoginLog.StatusCode = field.NewInt32(tableName, "status_code")
	_adminLoginLog.Success = field.NewBool(tableName, "success")
	_adminLoginLog.Reason = field.NewString(tableName, "reason")
	_adminLoginLog.Location = field.NewString(tableName, "location")

	_adminLoginLog.fillFieldMap()

	return _adminLoginLog
}

type adminLoginLog struct {
	adminLoginLogDo adminLoginLogDo

	ALL            field.Asterisk
	ID             field.Int32  // id
	CreatedAt      field.Time   // 创建时间
	LoginIP        field.String // 登录IP地址
	LoginMac       field.String // 登录MAC地址
	LoginTime      field.Time   // 登录时间
	UserAgent      field.String // 浏览器的用户代理信息
	BrowserName    field.String // 浏览器名称
	BrowserVersion field.String // 浏览器版本
	ClientID       field.String // 客户端ID
	ClientName     field.String // 客户端名称
	OsName         field.String // 操作系统名称
	OsVersion      field.String // 操作系统版本
	UserID         field.Int64  // 操作者用户ID
	Username       field.String // 操作者账号名
	StatusCode     field.Int32  // 状态码
	Success        field.Bool   // 操作成功
	Reason         field.String // 登录失败原因
	Location       field.String // 登录地理位置

	fieldMap map[string]field.Expr
}

func (a adminLoginLog) Table(newTableName string) *adminLoginLog {
	a.adminLoginLogDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a adminLoginLog) As(alias string) *adminLoginLog {
	a.adminLoginLogDo.DO = *(a.adminLoginLogDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *adminLoginLog) updateTableName(table string) *adminLoginLog {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt32(table, "id")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.LoginIP = field.NewString(table, "login_ip")
	a.LoginMac = field.NewString(table, "login_mac")
	a.LoginTime = field.NewTime(table, "login_time")
	a.UserAgent = field.NewString(table, "user_agent")
	a.BrowserName = field.NewString(table, "browser_name")
	a.BrowserVersion = field.NewString(table, "browser_version")
	a.ClientID = field.NewString(table, "client_id")
	a.ClientName = field.NewString(table, "client_name")
	a.OsName = field.NewString(table, "os_name")
	a.OsVersion = field.NewString(table, "os_version")
	a.UserID = field.NewInt64(table, "user_id")
	a.Username = field.NewString(table, "username")
	a.StatusCode = field.NewInt32(table, "status_code")
	a.Success = field.NewBool(table, "success")
	a.Reason = field.NewString(table, "reason")
	a.Location = field.NewString(table, "location")

	a.fillFieldMap()

	return a
}

func (a *adminLoginLog) WithContext(ctx context.Context) IAdminLoginLogDo {
	return a.adminLoginLogDo.WithContext(ctx)
}

func (a adminLoginLog) TableName() string { return a.adminLoginLogDo.TableName() }

func (a adminLoginLog) Alias() string { return a.adminLoginLogDo.Alias() }

func (a adminLoginLog) Columns(cols ...field.Expr) gen.Columns {
	return a.adminLoginLogDo.Columns(cols...)
}

func (a *adminLoginLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *adminLoginLog) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 18)
	a.fieldMap["id"] = a.ID
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["login_ip"] = a.LoginIP
	a.fieldMap["login_mac"] = a.LoginMac
	a.fieldMap["login_time"] = a.LoginTime
	a.fieldMap["user_agent"] = a.UserAgent
	a.fieldMap["browser_name"] = a.BrowserName
	a.fieldMap["browser_version"] = a.BrowserVersion
	a.fieldMap["client_id"] = a.ClientID
	a.fieldMap["client_name"] = a.ClientName
	a.fieldMap["os_name"] = a.OsName
	a.fieldMap["os_version"] = a.OsVersion
	a.fieldMap["user_id"] = a.UserID
	a.fieldMap["username"] = a.Username
	a.fieldMap["status_code"] = a.StatusCode
	a.fieldMap["success"] = a.Success
	a.fieldMap["reason"] = a.Reason
	a.fieldMap["location"] = a.Location
}

func (a adminLoginLog) clone(db *gorm.DB) adminLoginLog {
	a.adminLoginLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a adminLoginLog) replaceDB(db *gorm.DB) adminLoginLog {
	a.adminLoginLogDo.ReplaceDB(db)
	return a
}

type adminLoginLogDo struct{ gen.DO }

type IAdminLoginLogDo interface {
	gen.SubQuery
	Debug() IAdminLoginLogDo
	WithContext(ctx context.Context) IAdminLoginLogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAdminLoginLogDo
	WriteDB() IAdminLoginLogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAdminLoginLogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAdminLoginLogDo
	Not(conds ...gen.Condition) IAdminLoginLogDo
	Or(conds ...gen.Condition) IAdminLoginLogDo
	Select(conds ...field.Expr) IAdminLoginLogDo
	Where(conds ...gen.Condition) IAdminLoginLogDo
	Order(conds ...field.Expr) IAdminLoginLogDo
	Distinct(cols ...field.Expr) IAdminLoginLogDo
	Omit(cols ...field.Expr) IAdminLoginLogDo
	Join(table schema.Tabler, on ...field.Expr) IAdminLoginLogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAdminLoginLogDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAdminLoginLogDo
	Group(cols ...field.Expr) IAdminLoginLogDo
	Having(conds ...gen.Condition) IAdminLoginLogDo
	Limit(limit int) IAdminLoginLogDo
	Offset(offset int) IAdminLoginLogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAdminLoginLogDo
	Unscoped() IAdminLoginLogDo
	Create(values ...*model.AdminLoginLog) error
	CreateInBatches(values []*model.AdminLoginLog, batchSize int) error
	Save(values ...*model.AdminLoginLog) error
	First() (*model.AdminLoginLog, error)
	Take() (*model.AdminLoginLog, error)
	Last() (*model.AdminLoginLog, error)
	Find() ([]*model.AdminLoginLog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AdminLoginLog, err error)
	FindInBatches(result *[]*model.AdminLoginLog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AdminLoginLog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAdminLoginLogDo
	Assign(attrs ...field.AssignExpr) IAdminLoginLogDo
	Joins(fields ...field.RelationField) IAdminLoginLogDo
	Preload(fields ...field.RelationField) IAdminLoginLogDo
	FirstOrInit() (*model.AdminLoginLog, error)
	FirstOrCreate() (*model.AdminLoginLog, error)
	FindByPage(offset int, limit int) (result []*model.AdminLoginLog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAdminLoginLogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a adminLoginLogDo) Debug() IAdminLoginLogDo {
	return a.withDO(a.DO.Debug())
}

func (a adminLoginLogDo) WithContext(ctx context.Context) IAdminLoginLogDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a adminLoginLogDo) ReadDB() IAdminLoginLogDo {
	return a.Clauses(dbresolver.Read)
}

func (a adminLoginLogDo) WriteDB() IAdminLoginLogDo {
	return a.Clauses(dbresolver.Write)
}

func (a adminLoginLogDo) Session(config *gorm.Session) IAdminLoginLogDo {
	return a.withDO(a.DO.Session(config))
}

func (a adminLoginLogDo) Clauses(conds ...clause.Expression) IAdminLoginLogDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a adminLoginLogDo) Returning(value interface{}, columns ...string) IAdminLoginLogDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a adminLoginLogDo) Not(conds ...gen.Condition) IAdminLoginLogDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a adminLoginLogDo) Or(conds ...gen.Condition) IAdminLoginLogDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a adminLoginLogDo) Select(conds ...field.Expr) IAdminLoginLogDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a adminLoginLogDo) Where(conds ...gen.Condition) IAdminLoginLogDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a adminLoginLogDo) Order(conds ...field.Expr) IAdminLoginLogDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a adminLoginLogDo) Distinct(cols ...field.Expr) IAdminLoginLogDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a adminLoginLogDo) Omit(cols ...field.Expr) IAdminLoginLogDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a adminLoginLogDo) Join(table schema.Tabler, on ...field.Expr) IAdminLoginLogDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a adminLoginLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAdminLoginLogDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a adminLoginLogDo) RightJoin(table schema.Tabler, on ...field.Expr) IAdminLoginLogDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a adminLoginLogDo) Group(cols ...field.Expr) IAdminLoginLogDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a adminLoginLogDo) Having(conds ...gen.Condition) IAdminLoginLogDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a adminLoginLogDo) Limit(limit int) IAdminLoginLogDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a adminLoginLogDo) Offset(offset int) IAdminLoginLogDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a adminLoginLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAdminLoginLogDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a adminLoginLogDo) Unscoped() IAdminLoginLogDo {
	return a.withDO(a.DO.Unscoped())
}

func (a adminLoginLogDo) Create(values ...*model.AdminLoginLog) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a adminLoginLogDo) CreateInBatches(values []*model.AdminLoginLog, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a adminLoginLogDo) Save(values ...*model.AdminLoginLog) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a adminLoginLogDo) First() (*model.AdminLoginLog, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminLoginLog), nil
	}
}

func (a adminLoginLogDo) Take() (*model.AdminLoginLog, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminLoginLog), nil
	}
}

func (a adminLoginLogDo) Last() (*model.AdminLoginLog, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminLoginLog), nil
	}
}

func (a adminLoginLogDo) Find() ([]*model.AdminLoginLog, error) {
	result, err := a.DO.Find()
	return result.([]*model.AdminLoginLog), err
}

func (a adminLoginLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AdminLoginLog, err error) {
	buf := make([]*model.AdminLoginLog, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a adminLoginLogDo) FindInBatches(result *[]*model.AdminLoginLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a adminLoginLogDo) Attrs(attrs ...field.AssignExpr) IAdminLoginLogDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a adminLoginLogDo) Assign(attrs ...field.AssignExpr) IAdminLoginLogDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a adminLoginLogDo) Joins(fields ...field.RelationField) IAdminLoginLogDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a adminLoginLogDo) Preload(fields ...field.RelationField) IAdminLoginLogDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a adminLoginLogDo) FirstOrInit() (*model.AdminLoginLog, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminLoginLog), nil
	}
}

func (a adminLoginLogDo) FirstOrCreate() (*model.AdminLoginLog, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminLoginLog), nil
	}
}

func (a adminLoginLogDo) FindByPage(offset int, limit int) (result []*model.AdminLoginLog, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a adminLoginLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a adminLoginLogDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a adminLoginLogDo) Delete(models ...*model.AdminLoginLog) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *adminLoginLogDo) withDO(do gen.Dao) *adminLoginLogDo {
	a.DO = *do.(*gen.DO)
	return a
}
