// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                            = new(Query)
	AdminLoginLog                *adminLoginLog
	AdminLoginRestriction        *adminLoginRestriction
	AdminOperationLog            *adminOperationLog
	Department                   *department
	File                         *file
	NotificationMessage          *notificationMessage
	NotificationMessageCategory  *notificationMessageCategory
	NotificationMessageRecipient *notificationMessageRecipient
	Organization                 *organization
	Position                     *position
	PrivateMessage               *privateMessage
	SysAPIResource               *sysAPIResource
	SysDict                      *sysDict
	SysMenu                      *sysMenu
	SysRole                      *sysRole
	SysTask                      *sysTask
	Tenant                       *tenant
	User                         *user
	UserCredential               *userCredential
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	AdminLoginLog = &Q.AdminLoginLog
	AdminLoginRestriction = &Q.AdminLoginRestriction
	AdminOperationLog = &Q.AdminOperationLog
	Department = &Q.Department
	File = &Q.File
	NotificationMessage = &Q.NotificationMessage
	NotificationMessageCategory = &Q.NotificationMessageCategory
	NotificationMessageRecipient = &Q.NotificationMessageRecipient
	Organization = &Q.Organization
	Position = &Q.Position
	PrivateMessage = &Q.PrivateMessage
	SysAPIResource = &Q.SysAPIResource
	SysDict = &Q.SysDict
	SysMenu = &Q.SysMenu
	SysRole = &Q.SysRole
	SysTask = &Q.SysTask
	Tenant = &Q.Tenant
	User = &Q.User
	UserCredential = &Q.UserCredential
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                           db,
		AdminLoginLog:                newAdminLoginLog(db, opts...),
		AdminLoginRestriction:        newAdminLoginRestriction(db, opts...),
		AdminOperationLog:            newAdminOperationLog(db, opts...),
		Department:                   newDepartment(db, opts...),
		File:                         newFile(db, opts...),
		NotificationMessage:          newNotificationMessage(db, opts...),
		NotificationMessageCategory:  newNotificationMessageCategory(db, opts...),
		NotificationMessageRecipient: newNotificationMessageRecipient(db, opts...),
		Organization:                 newOrganization(db, opts...),
		Position:                     newPosition(db, opts...),
		PrivateMessage:               newPrivateMessage(db, opts...),
		SysAPIResource:               newSysAPIResource(db, opts...),
		SysDict:                      newSysDict(db, opts...),
		SysMenu:                      newSysMenu(db, opts...),
		SysRole:                      newSysRole(db, opts...),
		SysTask:                      newSysTask(db, opts...),
		Tenant:                       newTenant(db, opts...),
		User:                         newUser(db, opts...),
		UserCredential:               newUserCredential(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	AdminLoginLog                adminLoginLog
	AdminLoginRestriction        adminLoginRestriction
	AdminOperationLog            adminOperationLog
	Department                   department
	File                         file
	NotificationMessage          notificationMessage
	NotificationMessageCategory  notificationMessageCategory
	NotificationMessageRecipient notificationMessageRecipient
	Organization                 organization
	Position                     position
	PrivateMessage               privateMessage
	SysAPIResource               sysAPIResource
	SysDict                      sysDict
	SysMenu                      sysMenu
	SysRole                      sysRole
	SysTask                      sysTask
	Tenant                       tenant
	User                         user
	UserCredential               userCredential
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                           db,
		AdminLoginLog:                q.AdminLoginLog.clone(db),
		AdminLoginRestriction:        q.AdminLoginRestriction.clone(db),
		AdminOperationLog:            q.AdminOperationLog.clone(db),
		Department:                   q.Department.clone(db),
		File:                         q.File.clone(db),
		NotificationMessage:          q.NotificationMessage.clone(db),
		NotificationMessageCategory:  q.NotificationMessageCategory.clone(db),
		NotificationMessageRecipient: q.NotificationMessageRecipient.clone(db),
		Organization:                 q.Organization.clone(db),
		Position:                     q.Position.clone(db),
		PrivateMessage:               q.PrivateMessage.clone(db),
		SysAPIResource:               q.SysAPIResource.clone(db),
		SysDict:                      q.SysDict.clone(db),
		SysMenu:                      q.SysMenu.clone(db),
		SysRole:                      q.SysRole.clone(db),
		SysTask:                      q.SysTask.clone(db),
		Tenant:                       q.Tenant.clone(db),
		User:                         q.User.clone(db),
		UserCredential:               q.UserCredential.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                           db,
		AdminLoginLog:                q.AdminLoginLog.replaceDB(db),
		AdminLoginRestriction:        q.AdminLoginRestriction.replaceDB(db),
		AdminOperationLog:            q.AdminOperationLog.replaceDB(db),
		Department:                   q.Department.replaceDB(db),
		File:                         q.File.replaceDB(db),
		NotificationMessage:          q.NotificationMessage.replaceDB(db),
		NotificationMessageCategory:  q.NotificationMessageCategory.replaceDB(db),
		NotificationMessageRecipient: q.NotificationMessageRecipient.replaceDB(db),
		Organization:                 q.Organization.replaceDB(db),
		Position:                     q.Position.replaceDB(db),
		PrivateMessage:               q.PrivateMessage.replaceDB(db),
		SysAPIResource:               q.SysAPIResource.replaceDB(db),
		SysDict:                      q.SysDict.replaceDB(db),
		SysMenu:                      q.SysMenu.replaceDB(db),
		SysRole:                      q.SysRole.replaceDB(db),
		SysTask:                      q.SysTask.replaceDB(db),
		Tenant:                       q.Tenant.replaceDB(db),
		User:                         q.User.replaceDB(db),
		UserCredential:               q.UserCredential.replaceDB(db),
	}
}

type queryCtx struct {
	AdminLoginLog                IAdminLoginLogDo
	AdminLoginRestriction        IAdminLoginRestrictionDo
	AdminOperationLog            IAdminOperationLogDo
	Department                   IDepartmentDo
	File                         IFileDo
	NotificationMessage          INotificationMessageDo
	NotificationMessageCategory  INotificationMessageCategoryDo
	NotificationMessageRecipient INotificationMessageRecipientDo
	Organization                 IOrganizationDo
	Position                     IPositionDo
	PrivateMessage               IPrivateMessageDo
	SysAPIResource               ISysAPIResourceDo
	SysDict                      ISysDictDo
	SysMenu                      ISysMenuDo
	SysRole                      ISysRoleDo
	SysTask                      ISysTaskDo
	Tenant                       ITenantDo
	User                         IUserDo
	UserCredential               IUserCredentialDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		AdminLoginLog:                q.AdminLoginLog.WithContext(ctx),
		AdminLoginRestriction:        q.AdminLoginRestriction.WithContext(ctx),
		AdminOperationLog:            q.AdminOperationLog.WithContext(ctx),
		Department:                   q.Department.WithContext(ctx),
		File:                         q.File.WithContext(ctx),
		NotificationMessage:          q.NotificationMessage.WithContext(ctx),
		NotificationMessageCategory:  q.NotificationMessageCategory.WithContext(ctx),
		NotificationMessageRecipient: q.NotificationMessageRecipient.WithContext(ctx),
		Organization:                 q.Organization.WithContext(ctx),
		Position:                     q.Position.WithContext(ctx),
		PrivateMessage:               q.PrivateMessage.WithContext(ctx),
		SysAPIResource:               q.SysAPIResource.WithContext(ctx),
		SysDict:                      q.SysDict.WithContext(ctx),
		SysMenu:                      q.SysMenu.WithContext(ctx),
		SysRole:                      q.SysRole.WithContext(ctx),
		SysTask:                      q.SysTask.WithContext(ctx),
		Tenant:                       q.Tenant.WithContext(ctx),
		User:                         q.User.WithContext(ctx),
		UserCredential:               q.UserCredential.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
