// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"kratos-admin/app/admin/service/internal/data/gorm/model"
)

func newNotificationMessage(db *gorm.DB, opts ...gen.DOOption) notificationMessage {
	_notificationMessage := notificationMessage{}

	_notificationMessage.notificationMessageDo.UseDB(db, opts...)
	_notificationMessage.notificationMessageDo.UseModel(&model.NotificationMessage{})

	tableName := _notificationMessage.notificationMessageDo.TableName()
	_notificationMessage.ALL = field.NewAsterisk(tableName)
	_notificationMessage.ID = field.NewInt32(tableName, "id")
	_notificationMessage.CreatedAt = field.NewTime(tableName, "created_at")
	_notificationMessage.UpdatedAt = field.NewTime(tableName, "updated_at")
	_notificationMessage.DeletedAt = field.NewTime(tableName, "deleted_at")
	_notificationMessage.CreateBy = field.NewInt64(tableName, "create_by")
	_notificationMessage.UpdateBy = field.NewInt64(tableName, "update_by")
	_notificationMessage.TenantID = field.NewInt64(tableName, "tenant_id")
	_notificationMessage.Subject = field.NewString(tableName, "subject")
	_notificationMessage.Content = field.NewString(tableName, "content")
	_notificationMessage.CategoryID = field.NewInt64(tableName, "category_id")
	_notificationMessage.Status = field.NewString(tableName, "status")

	_notificationMessage.fillFieldMap()

	return _notificationMessage
}

type notificationMessage struct {
	notificationMessageDo notificationMessageDo

	ALL        field.Asterisk
	ID         field.Int32  // id
	CreatedAt  field.Time   // 创建时间
	UpdatedAt  field.Time   // 更新时间
	DeletedAt  field.Time   // 删除时间
	CreateBy   field.Int64  // 创建者ID
	UpdateBy   field.Int64  // 更新者ID
	TenantID   field.Int64  // 租户ID
	Subject    field.String // 主题
	Content    field.String // 内容
	CategoryID field.Int64  // 分类ID
	Status     field.String // 消息状态

	fieldMap map[string]field.Expr
}

func (n notificationMessage) Table(newTableName string) *notificationMessage {
	n.notificationMessageDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n notificationMessage) As(alias string) *notificationMessage {
	n.notificationMessageDo.DO = *(n.notificationMessageDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *notificationMessage) updateTableName(table string) *notificationMessage {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewInt32(table, "id")
	n.CreatedAt = field.NewTime(table, "created_at")
	n.UpdatedAt = field.NewTime(table, "updated_at")
	n.DeletedAt = field.NewTime(table, "deleted_at")
	n.CreateBy = field.NewInt64(table, "create_by")
	n.UpdateBy = field.NewInt64(table, "update_by")
	n.TenantID = field.NewInt64(table, "tenant_id")
	n.Subject = field.NewString(table, "subject")
	n.Content = field.NewString(table, "content")
	n.CategoryID = field.NewInt64(table, "category_id")
	n.Status = field.NewString(table, "status")

	n.fillFieldMap()

	return n
}

func (n *notificationMessage) WithContext(ctx context.Context) INotificationMessageDo {
	return n.notificationMessageDo.WithContext(ctx)
}

func (n notificationMessage) TableName() string { return n.notificationMessageDo.TableName() }

func (n notificationMessage) Alias() string { return n.notificationMessageDo.Alias() }

func (n notificationMessage) Columns(cols ...field.Expr) gen.Columns {
	return n.notificationMessageDo.Columns(cols...)
}

func (n *notificationMessage) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *notificationMessage) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 11)
	n.fieldMap["id"] = n.ID
	n.fieldMap["created_at"] = n.CreatedAt
	n.fieldMap["updated_at"] = n.UpdatedAt
	n.fieldMap["deleted_at"] = n.DeletedAt
	n.fieldMap["create_by"] = n.CreateBy
	n.fieldMap["update_by"] = n.UpdateBy
	n.fieldMap["tenant_id"] = n.TenantID
	n.fieldMap["subject"] = n.Subject
	n.fieldMap["content"] = n.Content
	n.fieldMap["category_id"] = n.CategoryID
	n.fieldMap["status"] = n.Status
}

func (n notificationMessage) clone(db *gorm.DB) notificationMessage {
	n.notificationMessageDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n notificationMessage) replaceDB(db *gorm.DB) notificationMessage {
	n.notificationMessageDo.ReplaceDB(db)
	return n
}

type notificationMessageDo struct{ gen.DO }

type INotificationMessageDo interface {
	gen.SubQuery
	Debug() INotificationMessageDo
	WithContext(ctx context.Context) INotificationMessageDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INotificationMessageDo
	WriteDB() INotificationMessageDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INotificationMessageDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INotificationMessageDo
	Not(conds ...gen.Condition) INotificationMessageDo
	Or(conds ...gen.Condition) INotificationMessageDo
	Select(conds ...field.Expr) INotificationMessageDo
	Where(conds ...gen.Condition) INotificationMessageDo
	Order(conds ...field.Expr) INotificationMessageDo
	Distinct(cols ...field.Expr) INotificationMessageDo
	Omit(cols ...field.Expr) INotificationMessageDo
	Join(table schema.Tabler, on ...field.Expr) INotificationMessageDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INotificationMessageDo
	RightJoin(table schema.Tabler, on ...field.Expr) INotificationMessageDo
	Group(cols ...field.Expr) INotificationMessageDo
	Having(conds ...gen.Condition) INotificationMessageDo
	Limit(limit int) INotificationMessageDo
	Offset(offset int) INotificationMessageDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INotificationMessageDo
	Unscoped() INotificationMessageDo
	Create(values ...*model.NotificationMessage) error
	CreateInBatches(values []*model.NotificationMessage, batchSize int) error
	Save(values ...*model.NotificationMessage) error
	First() (*model.NotificationMessage, error)
	Take() (*model.NotificationMessage, error)
	Last() (*model.NotificationMessage, error)
	Find() ([]*model.NotificationMessage, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NotificationMessage, err error)
	FindInBatches(result *[]*model.NotificationMessage, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.NotificationMessage) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INotificationMessageDo
	Assign(attrs ...field.AssignExpr) INotificationMessageDo
	Joins(fields ...field.RelationField) INotificationMessageDo
	Preload(fields ...field.RelationField) INotificationMessageDo
	FirstOrInit() (*model.NotificationMessage, error)
	FirstOrCreate() (*model.NotificationMessage, error)
	FindByPage(offset int, limit int) (result []*model.NotificationMessage, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INotificationMessageDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n notificationMessageDo) Debug() INotificationMessageDo {
	return n.withDO(n.DO.Debug())
}

func (n notificationMessageDo) WithContext(ctx context.Context) INotificationMessageDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n notificationMessageDo) ReadDB() INotificationMessageDo {
	return n.Clauses(dbresolver.Read)
}

func (n notificationMessageDo) WriteDB() INotificationMessageDo {
	return n.Clauses(dbresolver.Write)
}

func (n notificationMessageDo) Session(config *gorm.Session) INotificationMessageDo {
	return n.withDO(n.DO.Session(config))
}

func (n notificationMessageDo) Clauses(conds ...clause.Expression) INotificationMessageDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n notificationMessageDo) Returning(value interface{}, columns ...string) INotificationMessageDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n notificationMessageDo) Not(conds ...gen.Condition) INotificationMessageDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n notificationMessageDo) Or(conds ...gen.Condition) INotificationMessageDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n notificationMessageDo) Select(conds ...field.Expr) INotificationMessageDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n notificationMessageDo) Where(conds ...gen.Condition) INotificationMessageDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n notificationMessageDo) Order(conds ...field.Expr) INotificationMessageDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n notificationMessageDo) Distinct(cols ...field.Expr) INotificationMessageDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n notificationMessageDo) Omit(cols ...field.Expr) INotificationMessageDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n notificationMessageDo) Join(table schema.Tabler, on ...field.Expr) INotificationMessageDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n notificationMessageDo) LeftJoin(table schema.Tabler, on ...field.Expr) INotificationMessageDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n notificationMessageDo) RightJoin(table schema.Tabler, on ...field.Expr) INotificationMessageDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n notificationMessageDo) Group(cols ...field.Expr) INotificationMessageDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n notificationMessageDo) Having(conds ...gen.Condition) INotificationMessageDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n notificationMessageDo) Limit(limit int) INotificationMessageDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n notificationMessageDo) Offset(offset int) INotificationMessageDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n notificationMessageDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INotificationMessageDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n notificationMessageDo) Unscoped() INotificationMessageDo {
	return n.withDO(n.DO.Unscoped())
}

func (n notificationMessageDo) Create(values ...*model.NotificationMessage) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n notificationMessageDo) CreateInBatches(values []*model.NotificationMessage, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n notificationMessageDo) Save(values ...*model.NotificationMessage) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n notificationMessageDo) First() (*model.NotificationMessage, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotificationMessage), nil
	}
}

func (n notificationMessageDo) Take() (*model.NotificationMessage, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotificationMessage), nil
	}
}

func (n notificationMessageDo) Last() (*model.NotificationMessage, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotificationMessage), nil
	}
}

func (n notificationMessageDo) Find() ([]*model.NotificationMessage, error) {
	result, err := n.DO.Find()
	return result.([]*model.NotificationMessage), err
}

func (n notificationMessageDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NotificationMessage, err error) {
	buf := make([]*model.NotificationMessage, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n notificationMessageDo) FindInBatches(result *[]*model.NotificationMessage, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n notificationMessageDo) Attrs(attrs ...field.AssignExpr) INotificationMessageDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n notificationMessageDo) Assign(attrs ...field.AssignExpr) INotificationMessageDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n notificationMessageDo) Joins(fields ...field.RelationField) INotificationMessageDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n notificationMessageDo) Preload(fields ...field.RelationField) INotificationMessageDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n notificationMessageDo) FirstOrInit() (*model.NotificationMessage, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotificationMessage), nil
	}
}

func (n notificationMessageDo) FirstOrCreate() (*model.NotificationMessage, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotificationMessage), nil
	}
}

func (n notificationMessageDo) FindByPage(offset int, limit int) (result []*model.NotificationMessage, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n notificationMessageDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n notificationMessageDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n notificationMessageDo) Delete(models ...*model.NotificationMessage) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *notificationMessageDo) withDO(do gen.Dao) *notificationMessageDo {
	n.DO = *do.(*gen.DO)
	return n
}
