// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"kratos-admin/app/admin/service/internal/data/gorm/model"
)

func newNotificationMessageRecipient(db *gorm.DB, opts ...gen.DOOption) notificationMessageRecipient {
	_notificationMessageRecipient := notificationMessageRecipient{}

	_notificationMessageRecipient.notificationMessageRecipientDo.UseDB(db, opts...)
	_notificationMessageRecipient.notificationMessageRecipientDo.UseModel(&model.NotificationMessageRecipient{})

	tableName := _notificationMessageRecipient.notificationMessageRecipientDo.TableName()
	_notificationMessageRecipient.ALL = field.NewAsterisk(tableName)
	_notificationMessageRecipient.ID = field.NewInt32(tableName, "id")
	_notificationMessageRecipient.CreatedAt = field.NewTime(tableName, "created_at")
	_notificationMessageRecipient.UpdatedAt = field.NewTime(tableName, "updated_at")
	_notificationMessageRecipient.DeletedAt = field.NewTime(tableName, "deleted_at")
	_notificationMessageRecipient.TenantID = field.NewInt64(tableName, "tenant_id")
	_notificationMessageRecipient.MessageID = field.NewInt64(tableName, "message_id")
	_notificationMessageRecipient.RecipientID = field.NewInt64(tableName, "recipient_id")
	_notificationMessageRecipient.Status = field.NewString(tableName, "status")

	_notificationMessageRecipient.fillFieldMap()

	return _notificationMessageRecipient
}

type notificationMessageRecipient struct {
	notificationMessageRecipientDo notificationMessageRecipientDo

	ALL         field.Asterisk
	ID          field.Int32  // id
	CreatedAt   field.Time   // 创建时间
	UpdatedAt   field.Time   // 更新时间
	DeletedAt   field.Time   // 删除时间
	TenantID    field.Int64  // 租户ID
	MessageID   field.Int64  // 群发消息ID
	RecipientID field.Int64  // 接收者用户ID
	Status      field.String // 消息状态

	fieldMap map[string]field.Expr
}

func (n notificationMessageRecipient) Table(newTableName string) *notificationMessageRecipient {
	n.notificationMessageRecipientDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n notificationMessageRecipient) As(alias string) *notificationMessageRecipient {
	n.notificationMessageRecipientDo.DO = *(n.notificationMessageRecipientDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *notificationMessageRecipient) updateTableName(table string) *notificationMessageRecipient {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewInt32(table, "id")
	n.CreatedAt = field.NewTime(table, "created_at")
	n.UpdatedAt = field.NewTime(table, "updated_at")
	n.DeletedAt = field.NewTime(table, "deleted_at")
	n.TenantID = field.NewInt64(table, "tenant_id")
	n.MessageID = field.NewInt64(table, "message_id")
	n.RecipientID = field.NewInt64(table, "recipient_id")
	n.Status = field.NewString(table, "status")

	n.fillFieldMap()

	return n
}

func (n *notificationMessageRecipient) WithContext(ctx context.Context) INotificationMessageRecipientDo {
	return n.notificationMessageRecipientDo.WithContext(ctx)
}

func (n notificationMessageRecipient) TableName() string {
	return n.notificationMessageRecipientDo.TableName()
}

func (n notificationMessageRecipient) Alias() string { return n.notificationMessageRecipientDo.Alias() }

func (n notificationMessageRecipient) Columns(cols ...field.Expr) gen.Columns {
	return n.notificationMessageRecipientDo.Columns(cols...)
}

func (n *notificationMessageRecipient) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *notificationMessageRecipient) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 8)
	n.fieldMap["id"] = n.ID
	n.fieldMap["created_at"] = n.CreatedAt
	n.fieldMap["updated_at"] = n.UpdatedAt
	n.fieldMap["deleted_at"] = n.DeletedAt
	n.fieldMap["tenant_id"] = n.TenantID
	n.fieldMap["message_id"] = n.MessageID
	n.fieldMap["recipient_id"] = n.RecipientID
	n.fieldMap["status"] = n.Status
}

func (n notificationMessageRecipient) clone(db *gorm.DB) notificationMessageRecipient {
	n.notificationMessageRecipientDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n notificationMessageRecipient) replaceDB(db *gorm.DB) notificationMessageRecipient {
	n.notificationMessageRecipientDo.ReplaceDB(db)
	return n
}

type notificationMessageRecipientDo struct{ gen.DO }

type INotificationMessageRecipientDo interface {
	gen.SubQuery
	Debug() INotificationMessageRecipientDo
	WithContext(ctx context.Context) INotificationMessageRecipientDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INotificationMessageRecipientDo
	WriteDB() INotificationMessageRecipientDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INotificationMessageRecipientDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INotificationMessageRecipientDo
	Not(conds ...gen.Condition) INotificationMessageRecipientDo
	Or(conds ...gen.Condition) INotificationMessageRecipientDo
	Select(conds ...field.Expr) INotificationMessageRecipientDo
	Where(conds ...gen.Condition) INotificationMessageRecipientDo
	Order(conds ...field.Expr) INotificationMessageRecipientDo
	Distinct(cols ...field.Expr) INotificationMessageRecipientDo
	Omit(cols ...field.Expr) INotificationMessageRecipientDo
	Join(table schema.Tabler, on ...field.Expr) INotificationMessageRecipientDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INotificationMessageRecipientDo
	RightJoin(table schema.Tabler, on ...field.Expr) INotificationMessageRecipientDo
	Group(cols ...field.Expr) INotificationMessageRecipientDo
	Having(conds ...gen.Condition) INotificationMessageRecipientDo
	Limit(limit int) INotificationMessageRecipientDo
	Offset(offset int) INotificationMessageRecipientDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INotificationMessageRecipientDo
	Unscoped() INotificationMessageRecipientDo
	Create(values ...*model.NotificationMessageRecipient) error
	CreateInBatches(values []*model.NotificationMessageRecipient, batchSize int) error
	Save(values ...*model.NotificationMessageRecipient) error
	First() (*model.NotificationMessageRecipient, error)
	Take() (*model.NotificationMessageRecipient, error)
	Last() (*model.NotificationMessageRecipient, error)
	Find() ([]*model.NotificationMessageRecipient, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NotificationMessageRecipient, err error)
	FindInBatches(result *[]*model.NotificationMessageRecipient, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.NotificationMessageRecipient) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INotificationMessageRecipientDo
	Assign(attrs ...field.AssignExpr) INotificationMessageRecipientDo
	Joins(fields ...field.RelationField) INotificationMessageRecipientDo
	Preload(fields ...field.RelationField) INotificationMessageRecipientDo
	FirstOrInit() (*model.NotificationMessageRecipient, error)
	FirstOrCreate() (*model.NotificationMessageRecipient, error)
	FindByPage(offset int, limit int) (result []*model.NotificationMessageRecipient, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INotificationMessageRecipientDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n notificationMessageRecipientDo) Debug() INotificationMessageRecipientDo {
	return n.withDO(n.DO.Debug())
}

func (n notificationMessageRecipientDo) WithContext(ctx context.Context) INotificationMessageRecipientDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n notificationMessageRecipientDo) ReadDB() INotificationMessageRecipientDo {
	return n.Clauses(dbresolver.Read)
}

func (n notificationMessageRecipientDo) WriteDB() INotificationMessageRecipientDo {
	return n.Clauses(dbresolver.Write)
}

func (n notificationMessageRecipientDo) Session(config *gorm.Session) INotificationMessageRecipientDo {
	return n.withDO(n.DO.Session(config))
}

func (n notificationMessageRecipientDo) Clauses(conds ...clause.Expression) INotificationMessageRecipientDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n notificationMessageRecipientDo) Returning(value interface{}, columns ...string) INotificationMessageRecipientDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n notificationMessageRecipientDo) Not(conds ...gen.Condition) INotificationMessageRecipientDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n notificationMessageRecipientDo) Or(conds ...gen.Condition) INotificationMessageRecipientDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n notificationMessageRecipientDo) Select(conds ...field.Expr) INotificationMessageRecipientDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n notificationMessageRecipientDo) Where(conds ...gen.Condition) INotificationMessageRecipientDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n notificationMessageRecipientDo) Order(conds ...field.Expr) INotificationMessageRecipientDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n notificationMessageRecipientDo) Distinct(cols ...field.Expr) INotificationMessageRecipientDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n notificationMessageRecipientDo) Omit(cols ...field.Expr) INotificationMessageRecipientDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n notificationMessageRecipientDo) Join(table schema.Tabler, on ...field.Expr) INotificationMessageRecipientDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n notificationMessageRecipientDo) LeftJoin(table schema.Tabler, on ...field.Expr) INotificationMessageRecipientDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n notificationMessageRecipientDo) RightJoin(table schema.Tabler, on ...field.Expr) INotificationMessageRecipientDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n notificationMessageRecipientDo) Group(cols ...field.Expr) INotificationMessageRecipientDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n notificationMessageRecipientDo) Having(conds ...gen.Condition) INotificationMessageRecipientDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n notificationMessageRecipientDo) Limit(limit int) INotificationMessageRecipientDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n notificationMessageRecipientDo) Offset(offset int) INotificationMessageRecipientDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n notificationMessageRecipientDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INotificationMessageRecipientDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n notificationMessageRecipientDo) Unscoped() INotificationMessageRecipientDo {
	return n.withDO(n.DO.Unscoped())
}

func (n notificationMessageRecipientDo) Create(values ...*model.NotificationMessageRecipient) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n notificationMessageRecipientDo) CreateInBatches(values []*model.NotificationMessageRecipient, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n notificationMessageRecipientDo) Save(values ...*model.NotificationMessageRecipient) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n notificationMessageRecipientDo) First() (*model.NotificationMessageRecipient, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotificationMessageRecipient), nil
	}
}

func (n notificationMessageRecipientDo) Take() (*model.NotificationMessageRecipient, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotificationMessageRecipient), nil
	}
}

func (n notificationMessageRecipientDo) Last() (*model.NotificationMessageRecipient, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotificationMessageRecipient), nil
	}
}

func (n notificationMessageRecipientDo) Find() ([]*model.NotificationMessageRecipient, error) {
	result, err := n.DO.Find()
	return result.([]*model.NotificationMessageRecipient), err
}

func (n notificationMessageRecipientDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NotificationMessageRecipient, err error) {
	buf := make([]*model.NotificationMessageRecipient, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n notificationMessageRecipientDo) FindInBatches(result *[]*model.NotificationMessageRecipient, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n notificationMessageRecipientDo) Attrs(attrs ...field.AssignExpr) INotificationMessageRecipientDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n notificationMessageRecipientDo) Assign(attrs ...field.AssignExpr) INotificationMessageRecipientDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n notificationMessageRecipientDo) Joins(fields ...field.RelationField) INotificationMessageRecipientDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n notificationMessageRecipientDo) Preload(fields ...field.RelationField) INotificationMessageRecipientDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n notificationMessageRecipientDo) FirstOrInit() (*model.NotificationMessageRecipient, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotificationMessageRecipient), nil
	}
}

func (n notificationMessageRecipientDo) FirstOrCreate() (*model.NotificationMessageRecipient, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotificationMessageRecipient), nil
	}
}

func (n notificationMessageRecipientDo) FindByPage(offset int, limit int) (result []*model.NotificationMessageRecipient, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n notificationMessageRecipientDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n notificationMessageRecipientDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n notificationMessageRecipientDo) Delete(models ...*model.NotificationMessageRecipient) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *notificationMessageRecipientDo) withDO(do gen.Dao) *notificationMessageRecipientDo {
	n.DO = *do.(*gen.DO)
	return n
}
