// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"kratos-admin/app/admin/service/internal/data/gorm/model"
)

func newNotificationMessageCategory(db *gorm.DB, opts ...gen.DOOption) notificationMessageCategory {
	_notificationMessageCategory := notificationMessageCategory{}

	_notificationMessageCategory.notificationMessageCategoryDo.UseDB(db, opts...)
	_notificationMessageCategory.notificationMessageCategoryDo.UseModel(&model.NotificationMessageCategory{})

	tableName := _notificationMessageCategory.notificationMessageCategoryDo.TableName()
	_notificationMessageCategory.ALL = field.NewAsterisk(tableName)
	_notificationMessageCategory.ID = field.NewInt32(tableName, "id")
	_notificationMessageCategory.CreatedAt = field.NewTime(tableName, "created_at")
	_notificationMessageCategory.UpdatedAt = field.NewTime(tableName, "updated_at")
	_notificationMessageCategory.DeletedAt = field.NewTime(tableName, "deleted_at")
	_notificationMessageCategory.CreateBy = field.NewInt64(tableName, "create_by")
	_notificationMessageCategory.UpdateBy = field.NewInt64(tableName, "update_by")
	_notificationMessageCategory.Remark = field.NewString(tableName, "remark")
	_notificationMessageCategory.TenantID = field.NewInt64(tableName, "tenant_id")
	_notificationMessageCategory.Name = field.NewString(tableName, "name")
	_notificationMessageCategory.Code = field.NewString(tableName, "code")
	_notificationMessageCategory.SortID = field.NewInt32(tableName, "sort_id")
	_notificationMessageCategory.Enable = field.NewBool(tableName, "enable")
	_notificationMessageCategory.ParentID = field.NewInt32(tableName, "parent_id")

	_notificationMessageCategory.fillFieldMap()

	return _notificationMessageCategory
}

type notificationMessageCategory struct {
	notificationMessageCategoryDo notificationMessageCategoryDo

	ALL       field.Asterisk
	ID        field.Int32  // id
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间
	DeletedAt field.Time   // 删除时间
	CreateBy  field.Int64  // 创建者ID
	UpdateBy  field.Int64  // 更新者ID
	Remark    field.String // 备注
	TenantID  field.Int64  // 租户ID
	Name      field.String // 名称
	Code      field.String // 编码
	SortID    field.Int32  // 排序编号
	Enable    field.Bool   // 是否启用
	ParentID  field.Int32  // 父节点ID

	fieldMap map[string]field.Expr
}

func (n notificationMessageCategory) Table(newTableName string) *notificationMessageCategory {
	n.notificationMessageCategoryDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n notificationMessageCategory) As(alias string) *notificationMessageCategory {
	n.notificationMessageCategoryDo.DO = *(n.notificationMessageCategoryDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *notificationMessageCategory) updateTableName(table string) *notificationMessageCategory {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewInt32(table, "id")
	n.CreatedAt = field.NewTime(table, "created_at")
	n.UpdatedAt = field.NewTime(table, "updated_at")
	n.DeletedAt = field.NewTime(table, "deleted_at")
	n.CreateBy = field.NewInt64(table, "create_by")
	n.UpdateBy = field.NewInt64(table, "update_by")
	n.Remark = field.NewString(table, "remark")
	n.TenantID = field.NewInt64(table, "tenant_id")
	n.Name = field.NewString(table, "name")
	n.Code = field.NewString(table, "code")
	n.SortID = field.NewInt32(table, "sort_id")
	n.Enable = field.NewBool(table, "enable")
	n.ParentID = field.NewInt32(table, "parent_id")

	n.fillFieldMap()

	return n
}

func (n *notificationMessageCategory) WithContext(ctx context.Context) INotificationMessageCategoryDo {
	return n.notificationMessageCategoryDo.WithContext(ctx)
}

func (n notificationMessageCategory) TableName() string {
	return n.notificationMessageCategoryDo.TableName()
}

func (n notificationMessageCategory) Alias() string { return n.notificationMessageCategoryDo.Alias() }

func (n notificationMessageCategory) Columns(cols ...field.Expr) gen.Columns {
	return n.notificationMessageCategoryDo.Columns(cols...)
}

func (n *notificationMessageCategory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *notificationMessageCategory) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 13)
	n.fieldMap["id"] = n.ID
	n.fieldMap["created_at"] = n.CreatedAt
	n.fieldMap["updated_at"] = n.UpdatedAt
	n.fieldMap["deleted_at"] = n.DeletedAt
	n.fieldMap["create_by"] = n.CreateBy
	n.fieldMap["update_by"] = n.UpdateBy
	n.fieldMap["remark"] = n.Remark
	n.fieldMap["tenant_id"] = n.TenantID
	n.fieldMap["name"] = n.Name
	n.fieldMap["code"] = n.Code
	n.fieldMap["sort_id"] = n.SortID
	n.fieldMap["enable"] = n.Enable
	n.fieldMap["parent_id"] = n.ParentID
}

func (n notificationMessageCategory) clone(db *gorm.DB) notificationMessageCategory {
	n.notificationMessageCategoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n notificationMessageCategory) replaceDB(db *gorm.DB) notificationMessageCategory {
	n.notificationMessageCategoryDo.ReplaceDB(db)
	return n
}

type notificationMessageCategoryDo struct{ gen.DO }

type INotificationMessageCategoryDo interface {
	gen.SubQuery
	Debug() INotificationMessageCategoryDo
	WithContext(ctx context.Context) INotificationMessageCategoryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INotificationMessageCategoryDo
	WriteDB() INotificationMessageCategoryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INotificationMessageCategoryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INotificationMessageCategoryDo
	Not(conds ...gen.Condition) INotificationMessageCategoryDo
	Or(conds ...gen.Condition) INotificationMessageCategoryDo
	Select(conds ...field.Expr) INotificationMessageCategoryDo
	Where(conds ...gen.Condition) INotificationMessageCategoryDo
	Order(conds ...field.Expr) INotificationMessageCategoryDo
	Distinct(cols ...field.Expr) INotificationMessageCategoryDo
	Omit(cols ...field.Expr) INotificationMessageCategoryDo
	Join(table schema.Tabler, on ...field.Expr) INotificationMessageCategoryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INotificationMessageCategoryDo
	RightJoin(table schema.Tabler, on ...field.Expr) INotificationMessageCategoryDo
	Group(cols ...field.Expr) INotificationMessageCategoryDo
	Having(conds ...gen.Condition) INotificationMessageCategoryDo
	Limit(limit int) INotificationMessageCategoryDo
	Offset(offset int) INotificationMessageCategoryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INotificationMessageCategoryDo
	Unscoped() INotificationMessageCategoryDo
	Create(values ...*model.NotificationMessageCategory) error
	CreateInBatches(values []*model.NotificationMessageCategory, batchSize int) error
	Save(values ...*model.NotificationMessageCategory) error
	First() (*model.NotificationMessageCategory, error)
	Take() (*model.NotificationMessageCategory, error)
	Last() (*model.NotificationMessageCategory, error)
	Find() ([]*model.NotificationMessageCategory, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NotificationMessageCategory, err error)
	FindInBatches(result *[]*model.NotificationMessageCategory, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.NotificationMessageCategory) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INotificationMessageCategoryDo
	Assign(attrs ...field.AssignExpr) INotificationMessageCategoryDo
	Joins(fields ...field.RelationField) INotificationMessageCategoryDo
	Preload(fields ...field.RelationField) INotificationMessageCategoryDo
	FirstOrInit() (*model.NotificationMessageCategory, error)
	FirstOrCreate() (*model.NotificationMessageCategory, error)
	FindByPage(offset int, limit int) (result []*model.NotificationMessageCategory, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INotificationMessageCategoryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n notificationMessageCategoryDo) Debug() INotificationMessageCategoryDo {
	return n.withDO(n.DO.Debug())
}

func (n notificationMessageCategoryDo) WithContext(ctx context.Context) INotificationMessageCategoryDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n notificationMessageCategoryDo) ReadDB() INotificationMessageCategoryDo {
	return n.Clauses(dbresolver.Read)
}

func (n notificationMessageCategoryDo) WriteDB() INotificationMessageCategoryDo {
	return n.Clauses(dbresolver.Write)
}

func (n notificationMessageCategoryDo) Session(config *gorm.Session) INotificationMessageCategoryDo {
	return n.withDO(n.DO.Session(config))
}

func (n notificationMessageCategoryDo) Clauses(conds ...clause.Expression) INotificationMessageCategoryDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n notificationMessageCategoryDo) Returning(value interface{}, columns ...string) INotificationMessageCategoryDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n notificationMessageCategoryDo) Not(conds ...gen.Condition) INotificationMessageCategoryDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n notificationMessageCategoryDo) Or(conds ...gen.Condition) INotificationMessageCategoryDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n notificationMessageCategoryDo) Select(conds ...field.Expr) INotificationMessageCategoryDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n notificationMessageCategoryDo) Where(conds ...gen.Condition) INotificationMessageCategoryDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n notificationMessageCategoryDo) Order(conds ...field.Expr) INotificationMessageCategoryDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n notificationMessageCategoryDo) Distinct(cols ...field.Expr) INotificationMessageCategoryDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n notificationMessageCategoryDo) Omit(cols ...field.Expr) INotificationMessageCategoryDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n notificationMessageCategoryDo) Join(table schema.Tabler, on ...field.Expr) INotificationMessageCategoryDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n notificationMessageCategoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) INotificationMessageCategoryDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n notificationMessageCategoryDo) RightJoin(table schema.Tabler, on ...field.Expr) INotificationMessageCategoryDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n notificationMessageCategoryDo) Group(cols ...field.Expr) INotificationMessageCategoryDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n notificationMessageCategoryDo) Having(conds ...gen.Condition) INotificationMessageCategoryDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n notificationMessageCategoryDo) Limit(limit int) INotificationMessageCategoryDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n notificationMessageCategoryDo) Offset(offset int) INotificationMessageCategoryDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n notificationMessageCategoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INotificationMessageCategoryDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n notificationMessageCategoryDo) Unscoped() INotificationMessageCategoryDo {
	return n.withDO(n.DO.Unscoped())
}

func (n notificationMessageCategoryDo) Create(values ...*model.NotificationMessageCategory) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n notificationMessageCategoryDo) CreateInBatches(values []*model.NotificationMessageCategory, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n notificationMessageCategoryDo) Save(values ...*model.NotificationMessageCategory) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n notificationMessageCategoryDo) First() (*model.NotificationMessageCategory, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotificationMessageCategory), nil
	}
}

func (n notificationMessageCategoryDo) Take() (*model.NotificationMessageCategory, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotificationMessageCategory), nil
	}
}

func (n notificationMessageCategoryDo) Last() (*model.NotificationMessageCategory, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotificationMessageCategory), nil
	}
}

func (n notificationMessageCategoryDo) Find() ([]*model.NotificationMessageCategory, error) {
	result, err := n.DO.Find()
	return result.([]*model.NotificationMessageCategory), err
}

func (n notificationMessageCategoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NotificationMessageCategory, err error) {
	buf := make([]*model.NotificationMessageCategory, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n notificationMessageCategoryDo) FindInBatches(result *[]*model.NotificationMessageCategory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n notificationMessageCategoryDo) Attrs(attrs ...field.AssignExpr) INotificationMessageCategoryDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n notificationMessageCategoryDo) Assign(attrs ...field.AssignExpr) INotificationMessageCategoryDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n notificationMessageCategoryDo) Joins(fields ...field.RelationField) INotificationMessageCategoryDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n notificationMessageCategoryDo) Preload(fields ...field.RelationField) INotificationMessageCategoryDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n notificationMessageCategoryDo) FirstOrInit() (*model.NotificationMessageCategory, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotificationMessageCategory), nil
	}
}

func (n notificationMessageCategoryDo) FirstOrCreate() (*model.NotificationMessageCategory, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotificationMessageCategory), nil
	}
}

func (n notificationMessageCategoryDo) FindByPage(offset int, limit int) (result []*model.NotificationMessageCategory, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n notificationMessageCategoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n notificationMessageCategoryDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n notificationMessageCategoryDo) Delete(models ...*model.NotificationMessageCategory) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *notificationMessageCategoryDo) withDO(do gen.Dao) *notificationMessageCategoryDo {
	n.DO = *do.(*gen.DO)
	return n
}
