// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"kratos-admin/app/admin/service/internal/data/gorm/model"
)

func newSysDict(db *gorm.DB, opts ...gen.DOOption) sysDict {
	_sysDict := sysDict{}

	_sysDict.sysDictDo.UseDB(db, opts...)
	_sysDict.sysDictDo.UseModel(&model.SysDict{})

	tableName := _sysDict.sysDictDo.TableName()
	_sysDict.ALL = field.NewAsterisk(tableName)
	_sysDict.ID = field.NewInt32(tableName, "id")
	_sysDict.CreatedAt = field.NewTime(tableName, "created_at")
	_sysDict.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sysDict.DeletedAt = field.NewTime(tableName, "deleted_at")
	_sysDict.Status = field.NewString(tableName, "status")
	_sysDict.CreateBy = field.NewInt64(tableName, "create_by")
	_sysDict.UpdateBy = field.NewInt64(tableName, "update_by")
	_sysDict.Remark = field.NewString(tableName, "remark")
	_sysDict.TenantID = field.NewInt64(tableName, "tenant_id")
	_sysDict.Key = field.NewString(tableName, "key")
	_sysDict.Category = field.NewString(tableName, "category")
	_sysDict.CategoryDesc = field.NewString(tableName, "category_desc")
	_sysDict.Value = field.NewString(tableName, "value")
	_sysDict.ValueDesc = field.NewString(tableName, "value_desc")
	_sysDict.ValueDataType = field.NewString(tableName, "value_data_type")
	_sysDict.SortID = field.NewInt32(tableName, "sort_id")

	_sysDict.fillFieldMap()

	return _sysDict
}

type sysDict struct {
	sysDictDo sysDictDo

	ALL           field.Asterisk
	ID            field.Int32  // id
	CreatedAt     field.Time   // 创建时间
	UpdatedAt     field.Time   // 更新时间
	DeletedAt     field.Time   // 删除时间
	Status        field.String // 状态
	CreateBy      field.Int64  // 创建者ID
	UpdateBy      field.Int64  // 更新者ID
	Remark        field.String // 备注
	TenantID      field.Int64  // 租户ID
	Key           field.String // 字典键
	Category      field.String // 字典类型
	CategoryDesc  field.String // 字典类型名称
	Value         field.String // 字典值
	ValueDesc     field.String // 字典值名称
	ValueDataType field.String // 字典值数据类型
	SortID        field.Int32  // 排序ID

	fieldMap map[string]field.Expr
}

func (s sysDict) Table(newTableName string) *sysDict {
	s.sysDictDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysDict) As(alias string) *sysDict {
	s.sysDictDo.DO = *(s.sysDictDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysDict) updateTableName(table string) *sysDict {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt32(table, "id")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewTime(table, "deleted_at")
	s.Status = field.NewString(table, "status")
	s.CreateBy = field.NewInt64(table, "create_by")
	s.UpdateBy = field.NewInt64(table, "update_by")
	s.Remark = field.NewString(table, "remark")
	s.TenantID = field.NewInt64(table, "tenant_id")
	s.Key = field.NewString(table, "key")
	s.Category = field.NewString(table, "category")
	s.CategoryDesc = field.NewString(table, "category_desc")
	s.Value = field.NewString(table, "value")
	s.ValueDesc = field.NewString(table, "value_desc")
	s.ValueDataType = field.NewString(table, "value_data_type")
	s.SortID = field.NewInt32(table, "sort_id")

	s.fillFieldMap()

	return s
}

func (s *sysDict) WithContext(ctx context.Context) ISysDictDo { return s.sysDictDo.WithContext(ctx) }

func (s sysDict) TableName() string { return s.sysDictDo.TableName() }

func (s sysDict) Alias() string { return s.sysDictDo.Alias() }

func (s sysDict) Columns(cols ...field.Expr) gen.Columns { return s.sysDictDo.Columns(cols...) }

func (s *sysDict) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysDict) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 16)
	s.fieldMap["id"] = s.ID
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
	s.fieldMap["status"] = s.Status
	s.fieldMap["create_by"] = s.CreateBy
	s.fieldMap["update_by"] = s.UpdateBy
	s.fieldMap["remark"] = s.Remark
	s.fieldMap["tenant_id"] = s.TenantID
	s.fieldMap["key"] = s.Key
	s.fieldMap["category"] = s.Category
	s.fieldMap["category_desc"] = s.CategoryDesc
	s.fieldMap["value"] = s.Value
	s.fieldMap["value_desc"] = s.ValueDesc
	s.fieldMap["value_data_type"] = s.ValueDataType
	s.fieldMap["sort_id"] = s.SortID
}

func (s sysDict) clone(db *gorm.DB) sysDict {
	s.sysDictDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysDict) replaceDB(db *gorm.DB) sysDict {
	s.sysDictDo.ReplaceDB(db)
	return s
}

type sysDictDo struct{ gen.DO }

type ISysDictDo interface {
	gen.SubQuery
	Debug() ISysDictDo
	WithContext(ctx context.Context) ISysDictDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysDictDo
	WriteDB() ISysDictDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysDictDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysDictDo
	Not(conds ...gen.Condition) ISysDictDo
	Or(conds ...gen.Condition) ISysDictDo
	Select(conds ...field.Expr) ISysDictDo
	Where(conds ...gen.Condition) ISysDictDo
	Order(conds ...field.Expr) ISysDictDo
	Distinct(cols ...field.Expr) ISysDictDo
	Omit(cols ...field.Expr) ISysDictDo
	Join(table schema.Tabler, on ...field.Expr) ISysDictDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysDictDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysDictDo
	Group(cols ...field.Expr) ISysDictDo
	Having(conds ...gen.Condition) ISysDictDo
	Limit(limit int) ISysDictDo
	Offset(offset int) ISysDictDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysDictDo
	Unscoped() ISysDictDo
	Create(values ...*model.SysDict) error
	CreateInBatches(values []*model.SysDict, batchSize int) error
	Save(values ...*model.SysDict) error
	First() (*model.SysDict, error)
	Take() (*model.SysDict, error)
	Last() (*model.SysDict, error)
	Find() ([]*model.SysDict, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysDict, err error)
	FindInBatches(result *[]*model.SysDict, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SysDict) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysDictDo
	Assign(attrs ...field.AssignExpr) ISysDictDo
	Joins(fields ...field.RelationField) ISysDictDo
	Preload(fields ...field.RelationField) ISysDictDo
	FirstOrInit() (*model.SysDict, error)
	FirstOrCreate() (*model.SysDict, error)
	FindByPage(offset int, limit int) (result []*model.SysDict, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysDictDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysDictDo) Debug() ISysDictDo {
	return s.withDO(s.DO.Debug())
}

func (s sysDictDo) WithContext(ctx context.Context) ISysDictDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysDictDo) ReadDB() ISysDictDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysDictDo) WriteDB() ISysDictDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysDictDo) Session(config *gorm.Session) ISysDictDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysDictDo) Clauses(conds ...clause.Expression) ISysDictDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysDictDo) Returning(value interface{}, columns ...string) ISysDictDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysDictDo) Not(conds ...gen.Condition) ISysDictDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysDictDo) Or(conds ...gen.Condition) ISysDictDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysDictDo) Select(conds ...field.Expr) ISysDictDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysDictDo) Where(conds ...gen.Condition) ISysDictDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysDictDo) Order(conds ...field.Expr) ISysDictDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysDictDo) Distinct(cols ...field.Expr) ISysDictDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysDictDo) Omit(cols ...field.Expr) ISysDictDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysDictDo) Join(table schema.Tabler, on ...field.Expr) ISysDictDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysDictDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysDictDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysDictDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysDictDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysDictDo) Group(cols ...field.Expr) ISysDictDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysDictDo) Having(conds ...gen.Condition) ISysDictDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysDictDo) Limit(limit int) ISysDictDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysDictDo) Offset(offset int) ISysDictDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysDictDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysDictDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysDictDo) Unscoped() ISysDictDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysDictDo) Create(values ...*model.SysDict) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysDictDo) CreateInBatches(values []*model.SysDict, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysDictDo) Save(values ...*model.SysDict) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysDictDo) First() (*model.SysDict, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysDict), nil
	}
}

func (s sysDictDo) Take() (*model.SysDict, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysDict), nil
	}
}

func (s sysDictDo) Last() (*model.SysDict, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysDict), nil
	}
}

func (s sysDictDo) Find() ([]*model.SysDict, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysDict), err
}

func (s sysDictDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysDict, err error) {
	buf := make([]*model.SysDict, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysDictDo) FindInBatches(result *[]*model.SysDict, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysDictDo) Attrs(attrs ...field.AssignExpr) ISysDictDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysDictDo) Assign(attrs ...field.AssignExpr) ISysDictDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysDictDo) Joins(fields ...field.RelationField) ISysDictDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysDictDo) Preload(fields ...field.RelationField) ISysDictDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysDictDo) FirstOrInit() (*model.SysDict, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysDict), nil
	}
}

func (s sysDictDo) FirstOrCreate() (*model.SysDict, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysDict), nil
	}
}

func (s sysDictDo) FindByPage(offset int, limit int) (result []*model.SysDict, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysDictDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysDictDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysDictDo) Delete(models ...*model.SysDict) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysDictDo) withDO(do gen.Dao) *sysDictDo {
	s.DO = *do.(*gen.DO)
	return s
}
