// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAdminLoginRestriction = "admin_login_restrictions"

// AdminLoginRestriction mapped from table <admin_login_restrictions>
type AdminLoginRestriction struct {
	ID        int32      `gorm:"column:id;type:integer;primaryKey;autoIncrement:true;index:adminloginrestriction_id,priority:1;comment:id" json:"id"`                              // id
	CreatedAt *time.Time `gorm:"column:created_at;type:timestamp with time zone;comment:创建时间" json:"created_at"`                                                                   // 创建时间
	UpdatedAt *time.Time `gorm:"column:updated_at;type:timestamp with time zone;comment:更新时间" json:"updated_at"`                                                                   // 更新时间
	DeletedAt *time.Time `gorm:"column:deleted_at;type:timestamp with time zone;comment:删除时间" json:"deleted_at"`                                                                   // 删除时间
	CreateBy  *int64     `gorm:"column:create_by;type:bigint;comment:创建者ID" json:"create_by"`                                                                                      // 创建者ID
	UpdateBy  *int64     `gorm:"column:update_by;type:bigint;comment:更新者ID" json:"update_by"`                                                                                      // 更新者ID
	TargetID  *int64     `gorm:"column:target_id;type:bigint;uniqueIndex:adminloginrestriction_target_id_type_method,priority:1;comment:目标用户ID" json:"target_id"`                  // 目标用户ID
	Value     *string    `gorm:"column:value;type:character varying;comment:限制值（如IP地址、MAC地址或地区代码）" json:"value"`                                                                   // 限制值（如IP地址、MAC地址或地区代码）
	Reason    *string    `gorm:"column:reason;type:character varying;comment:限制原因" json:"reason"`                                                                                  // 限制原因
	Type      *string    `gorm:"column:type;type:character varying;uniqueIndex:adminloginrestriction_target_id_type_method,priority:2;default:BLACKLIST;comment:限制类型" json:"type"` // 限制类型
	Method    *string    `gorm:"column:method;type:character varying;uniqueIndex:adminloginrestriction_target_id_type_method,priority:3;default:IP;comment:限制方式" json:"method"`    // 限制方式
}

// TableName AdminLoginRestriction's table name
func (*AdminLoginRestriction) TableName() string {
	return TableNameAdminLoginRestriction
}
