// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAdminLoginLog = "admin_login_logs"

// AdminLoginLog mapped from table <admin_login_logs>
type AdminLoginLog struct {
	ID             int32      `gorm:"column:id;type:integer;primaryKey;autoIncrement:true;index:adminloginlog_id,priority:1;comment:id" json:"id"` // id
	CreatedAt      *time.Time `gorm:"column:created_at;type:timestamp with time zone;comment:创建时间" json:"created_at"`                              // 创建时间
	LoginIP        *string    `gorm:"column:login_ip;type:character varying;comment:登录IP地址" json:"login_ip"`                                       // 登录IP地址
	LoginMac       *string    `gorm:"column:login_mac;type:character varying;comment:登录MAC地址" json:"login_mac"`                                    // 登录MAC地址
	LoginTime      *time.Time `gorm:"column:login_time;type:timestamp with time zone;comment:登录时间" json:"login_time"`                              // 登录时间
	UserAgent      *string    `gorm:"column:user_agent;type:character varying;comment:浏览器的用户代理信息" json:"user_agent"`                               // 浏览器的用户代理信息
	BrowserName    *string    `gorm:"column:browser_name;type:character varying;comment:浏览器名称" json:"browser_name"`                                // 浏览器名称
	BrowserVersion *string    `gorm:"column:browser_version;type:character varying;comment:浏览器版本" json:"browser_version"`                          // 浏览器版本
	ClientID       *string    `gorm:"column:client_id;type:character varying;comment:客户端ID" json:"client_id"`                                      // 客户端ID
	ClientName     *string    `gorm:"column:client_name;type:character varying;comment:客户端名称" json:"client_name"`                                  // 客户端名称
	OsName         *string    `gorm:"column:os_name;type:character varying;comment:操作系统名称" json:"os_name"`                                         // 操作系统名称
	OsVersion      *string    `gorm:"column:os_version;type:character varying;comment:操作系统版本" json:"os_version"`                                   // 操作系统版本
	UserID         *int64     `gorm:"column:user_id;type:bigint;comment:操作者用户ID" json:"user_id"`                                                   // 操作者用户ID
	Username       *string    `gorm:"column:username;type:character varying;comment:操作者账号名" json:"username"`                                       // 操作者账号名
	StatusCode     *int32     `gorm:"column:status_code;type:integer;comment:状态码" json:"status_code"`                                              // 状态码
	Success        *bool      `gorm:"column:success;type:boolean;comment:操作成功" json:"success"`                                                     // 操作成功
	Reason         *string    `gorm:"column:reason;type:character varying;comment:登录失败原因" json:"reason"`                                           // 登录失败原因
	Location       *string    `gorm:"column:location;type:character varying;comment:登录地理位置" json:"location"`                                       // 登录地理位置
}

// TableName AdminLoginLog's table name
func (*AdminLoginLog) TableName() string {
	return TableNameAdminLoginLog
}
