// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAdminOperationLog = "admin_operation_logs"

// AdminOperationLog mapped from table <admin_operation_logs>
type AdminOperationLog struct {
	ID             int32      `gorm:"column:id;type:integer;primaryKey;autoIncrement:true;index:adminoperationlog_id,priority:1;comment:id" json:"id"` // id
	CreatedAt      *time.Time `gorm:"column:created_at;type:timestamp with time zone;comment:创建时间" json:"created_at"`                                  // 创建时间
	RequestID      *string    `gorm:"column:request_id;type:character varying;comment:请求ID" json:"request_id"`                                         // 请求ID
	Method         *string    `gorm:"column:method;type:character varying;comment:请求方法" json:"method"`                                                 // 请求方法
	Operation      *string    `gorm:"column:operation;type:character varying;comment:操作方法" json:"operation"`                                           // 操作方法
	Path           *string    `gorm:"column:path;type:character varying;comment:请求路径" json:"path"`                                                     // 请求路径
	Referer        *string    `gorm:"column:referer;type:character varying;comment:请求源" json:"referer"`                                                // 请求源
	RequestURI     *string    `gorm:"column:request_uri;type:character varying;comment:请求URI" json:"request_uri"`                                      // 请求URI
	RequestBody    *string    `gorm:"column:request_body;type:character varying;comment:请求体" json:"request_body"`                                      // 请求体
	RequestHeader  *string    `gorm:"column:request_header;type:character varying;comment:请求头" json:"request_header"`                                  // 请求头
	Response       *string    `gorm:"column:response;type:character varying;comment:响应信息" json:"response"`                                             // 响应信息
	CostTime       *float64   `gorm:"column:cost_time;type:double precision;comment:操作耗时" json:"cost_time"`                                            // 操作耗时
	UserID         *int64     `gorm:"column:user_id;type:bigint;comment:操作者用户ID" json:"user_id"`                                                       // 操作者用户ID
	Username       *string    `gorm:"column:username;type:character varying;comment:操作者账号名" json:"username"`                                           // 操作者账号名
	ClientIP       *string    `gorm:"column:client_ip;type:character varying;comment:操作者IP" json:"client_ip"`                                          // 操作者IP
	StatusCode     *int32     `gorm:"column:status_code;type:integer;comment:状态码" json:"status_code"`                                                  // 状态码
	Reason         *string    `gorm:"column:reason;type:character varying;comment:操作失败原因" json:"reason"`                                               // 操作失败原因
	Success        *bool      `gorm:"column:success;type:boolean;comment:操作成功" json:"success"`                                                         // 操作成功
	Location       *string    `gorm:"column:location;type:character varying;comment:操作地理位置" json:"location"`                                           // 操作地理位置
	UserAgent      *string    `gorm:"column:user_agent;type:character varying;comment:浏览器的用户代理信息" json:"user_agent"`                                   // 浏览器的用户代理信息
	BrowserName    *string    `gorm:"column:browser_name;type:character varying;comment:浏览器名称" json:"browser_name"`                                    // 浏览器名称
	BrowserVersion *string    `gorm:"column:browser_version;type:character varying;comment:浏览器版本" json:"browser_version"`                              // 浏览器版本
	ClientID       *string    `gorm:"column:client_id;type:character varying;comment:客户端ID" json:"client_id"`                                          // 客户端ID
	ClientName     *string    `gorm:"column:client_name;type:character varying;comment:客户端名称" json:"client_name"`                                      // 客户端名称
	OsName         *string    `gorm:"column:os_name;type:character varying;comment:操作系统名称" json:"os_name"`                                             // 操作系统名称
	OsVersion      *string    `gorm:"column:os_version;type:character varying;comment:操作系统版本" json:"os_version"`                                       // 操作系统版本
}

// TableName AdminOperationLog's table name
func (*AdminOperationLog) TableName() string {
	return TableNameAdminOperationLog
}
