// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDepartment = "departments"

// Department mapped from table <departments>
type Department struct {
	ID             int32      `gorm:"column:id;type:integer;primaryKey;autoIncrement:true;index:department_id,priority:1;comment:id" json:"id"` // id
	CreatedAt      *time.Time `gorm:"column:created_at;type:timestamp with time zone;comment:创建时间" json:"created_at"`                           // 创建时间
	UpdatedAt      *time.Time `gorm:"column:updated_at;type:timestamp with time zone;comment:更新时间" json:"updated_at"`                           // 更新时间
	DeletedAt      *time.Time `gorm:"column:deleted_at;type:timestamp with time zone;comment:删除时间" json:"deleted_at"`                           // 删除时间
	Status         *string    `gorm:"column:status;type:character varying;default:ON;comment:状态" json:"status"`                                 // 状态
	CreateBy       *int64     `gorm:"column:create_by;type:bigint;comment:创建者ID" json:"create_by"`                                              // 创建者ID
	UpdateBy       *int64     `gorm:"column:update_by;type:bigint;comment:更新者ID" json:"update_by"`                                              // 更新者ID
	Remark         *string    `gorm:"column:remark;type:character varying;comment:备注" json:"remark"`                                            // 备注
	TenantID       *int64     `gorm:"column:tenant_id;type:bigint;index:department_tenant_id,priority:1;comment:租户ID" json:"tenant_id"`         // 租户ID
	Name           *string    `gorm:"column:name;type:character varying;comment:名字" json:"name"`                                                // 名字
	OrganizationID *int64     `gorm:"column:organization_id;type:bigint;comment:所属组织ID" json:"organization_id"`                                 // 所属组织ID
	SortID         *int32     `gorm:"column:sort_id;type:integer;comment:排序ID" json:"sort_id"`                                                  // 排序ID
	ParentID       *int32     `gorm:"column:parent_id;type:integer;comment:上一层部门ID" json:"parent_id"`                                           // 上一层部门ID
}

// TableName Department's table name
func (*Department) TableName() string {
	return TableNameDepartment
}
