// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFile = "files"

// File mapped from table <files>
type File struct {
	ID            int32      `gorm:"column:id;type:integer;primaryKey;autoIncrement:true;index:file_id,priority:1;comment:id" json:"id"` // id
	CreatedAt     *time.Time `gorm:"column:created_at;type:timestamp with time zone;comment:创建时间" json:"created_at"`                     // 创建时间
	UpdatedAt     *time.Time `gorm:"column:updated_at;type:timestamp with time zone;comment:更新时间" json:"updated_at"`                     // 更新时间
	DeletedAt     *time.Time `gorm:"column:deleted_at;type:timestamp with time zone;comment:删除时间" json:"deleted_at"`                     // 删除时间
	CreateBy      *int64     `gorm:"column:create_by;type:bigint;comment:创建者ID" json:"create_by"`                                        // 创建者ID
	Remark        *string    `gorm:"column:remark;type:character varying;comment:备注" json:"remark"`                                      // 备注
	TenantID      *int64     `gorm:"column:tenant_id;type:bigint;index:file_tenant_id,priority:1;comment:租户ID" json:"tenant_id"`         // 租户ID
	Provider      *string    `gorm:"column:provider;type:character varying;comment:OSS供应商" json:"provider"`                              // OSS供应商
	BucketName    *string    `gorm:"column:bucket_name;type:character varying;comment:存储桶名称" json:"bucket_name"`                         // 存储桶名称
	FileDirectory *string    `gorm:"column:file_directory;type:character varying;comment:文件目录" json:"file_directory"`                    // 文件目录
	FileGUID      *string    `gorm:"column:file_guid;type:character varying;comment:文件Guid" json:"file_guid"`                            // 文件Guid
	SaveFileName  *string    `gorm:"column:save_file_name;type:character varying;comment:保存文件名" json:"save_file_name"`                   // 保存文件名
	FileName      *string    `gorm:"column:file_name;type:character varying;comment:文件名" json:"file_name"`                               // 文件名
	Extension     *string    `gorm:"column:extension;type:character varying;comment:文件扩展名" json:"extension"`                             // 文件扩展名
	Size          *int64     `gorm:"column:size;type:bigint;comment:文件字节长度" json:"size"`                                                 // 文件字节长度
	SizeFormat    *string    `gorm:"column:size_format;type:character varying;comment:文件大小格式化" json:"size_format"`                       // 文件大小格式化
	LinkURL       *string    `gorm:"column:link_url;type:character varying;comment:链接地址" json:"link_url"`                                // 链接地址
	Md5           *string    `gorm:"column:md5;type:character varying;comment:md5码，防止上传重复文件" json:"md5"`                                 // md5码，防止上传重复文件
}

// TableName File's table name
func (*File) TableName() string {
	return TableNameFile
}
