// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNotificationMessageCategory = "notification_message_categories"

// NotificationMessageCategory mapped from table <notification_message_categories>
type NotificationMessageCategory struct {
	ID        int32      `gorm:"column:id;type:integer;primaryKey;autoIncrement:true;index:notificationmessagecategory_id,priority:1;comment:id" json:"id"` // id
	CreatedAt *time.Time `gorm:"column:created_at;type:timestamp with time zone;comment:创建时间" json:"created_at"`                                            // 创建时间
	UpdatedAt *time.Time `gorm:"column:updated_at;type:timestamp with time zone;comment:更新时间" json:"updated_at"`                                            // 更新时间
	DeletedAt *time.Time `gorm:"column:deleted_at;type:timestamp with time zone;comment:删除时间" json:"deleted_at"`                                            // 删除时间
	CreateBy  *int64     `gorm:"column:create_by;type:bigint;comment:创建者ID" json:"create_by"`                                                               // 创建者ID
	UpdateBy  *int64     `gorm:"column:update_by;type:bigint;comment:更新者ID" json:"update_by"`                                                               // 更新者ID
	Remark    *string    `gorm:"column:remark;type:character varying;comment:备注" json:"remark"`                                                             // 备注
	TenantID  *int64     `gorm:"column:tenant_id;type:bigint;index:notificationmessagecategory_tenant_id,priority:1;comment:租户ID" json:"tenant_id"`         // 租户ID
	Name      *string    `gorm:"column:name;type:character varying;comment:名称" json:"name"`                                                                 // 名称
	Code      *string    `gorm:"column:code;type:character varying;comment:编码" json:"code"`                                                                 // 编码
	SortID    *int32     `gorm:"column:sort_id;type:integer;comment:排序编号" json:"sort_id"`                                                                   // 排序编号
	Enable    *bool      `gorm:"column:enable;type:boolean;comment:是否启用" json:"enable"`                                                                     // 是否启用
	ParentID  *int32     `gorm:"column:parent_id;type:integer;comment:父节点ID" json:"parent_id"`                                                              // 父节点ID
}

// TableName NotificationMessageCategory's table name
func (*NotificationMessageCategory) TableName() string {
	return TableNameNotificationMessageCategory
}
