// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNotificationMessageRecipient = "notification_message_recipients"

// NotificationMessageRecipient mapped from table <notification_message_recipients>
type NotificationMessageRecipient struct {
	ID          int32      `gorm:"column:id;type:integer;primaryKey;autoIncrement:true;index:notificationmessagerecipient_id,priority:1;comment:id" json:"id"` // id
	CreatedAt   *time.Time `gorm:"column:created_at;type:timestamp with time zone;comment:创建时间" json:"created_at"`                                             // 创建时间
	UpdatedAt   *time.Time `gorm:"column:updated_at;type:timestamp with time zone;comment:更新时间" json:"updated_at"`                                             // 更新时间
	DeletedAt   *time.Time `gorm:"column:deleted_at;type:timestamp with time zone;comment:删除时间" json:"deleted_at"`                                             // 删除时间
	TenantID    *int64     `gorm:"column:tenant_id;type:bigint;index:notificationmessagerecipient_tenant_id,priority:1;comment:租户ID" json:"tenant_id"`         // 租户ID
	MessageID   *int64     `gorm:"column:message_id;type:bigint;comment:群发消息ID" json:"message_id"`                                                             // 群发消息ID
	RecipientID *int64     `gorm:"column:recipient_id;type:bigint;comment:接收者用户ID" json:"recipient_id"`                                                        // 接收者用户ID
	Status      *string    `gorm:"column:status;type:character varying;comment:消息状态" json:"status"`                                                            // 消息状态
}

// TableName NotificationMessageRecipient's table name
func (*NotificationMessageRecipient) TableName() string {
	return TableNameNotificationMessageRecipient
}
