// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNotificationMessage = "notification_messages"

// NotificationMessage mapped from table <notification_messages>
type NotificationMessage struct {
	ID         int32      `gorm:"column:id;type:integer;primaryKey;autoIncrement:true;index:notificationmessage_id,priority:1;comment:id" json:"id"` // id
	CreatedAt  *time.Time `gorm:"column:created_at;type:timestamp with time zone;comment:创建时间" json:"created_at"`                                    // 创建时间
	UpdatedAt  *time.Time `gorm:"column:updated_at;type:timestamp with time zone;comment:更新时间" json:"updated_at"`                                    // 更新时间
	DeletedAt  *time.Time `gorm:"column:deleted_at;type:timestamp with time zone;comment:删除时间" json:"deleted_at"`                                    // 删除时间
	CreateBy   *int64     `gorm:"column:create_by;type:bigint;comment:创建者ID" json:"create_by"`                                                       // 创建者ID
	UpdateBy   *int64     `gorm:"column:update_by;type:bigint;comment:更新者ID" json:"update_by"`                                                       // 更新者ID
	TenantID   *int64     `gorm:"column:tenant_id;type:bigint;index:notificationmessage_tenant_id,priority:1;comment:租户ID" json:"tenant_id"`         // 租户ID
	Subject    *string    `gorm:"column:subject;type:character varying;comment:主题" json:"subject"`                                                   // 主题
	Content    *string    `gorm:"column:content;type:character varying;comment:内容" json:"content"`                                                   // 内容
	CategoryID *int64     `gorm:"column:category_id;type:bigint;comment:分类ID" json:"category_id"`                                                    // 分类ID
	Status     *string    `gorm:"column:status;type:character varying;comment:消息状态" json:"status"`                                                   // 消息状态
}

// TableName NotificationMessage's table name
func (*NotificationMessage) TableName() string {
	return TableNameNotificationMessage
}
