// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePrivateMessage = "private_messages"

// PrivateMessage mapped from table <private_messages>
type PrivateMessage struct {
	ID         int32      `gorm:"column:id;type:integer;primaryKey;autoIncrement:true;index:privatemessage_id,priority:1;comment:id" json:"id"` // id
	CreatedAt  *time.Time `gorm:"column:created_at;type:timestamp with time zone;comment:创建时间" json:"created_at"`                               // 创建时间
	UpdatedAt  *time.Time `gorm:"column:updated_at;type:timestamp with time zone;comment:更新时间" json:"updated_at"`                               // 更新时间
	DeletedAt  *time.Time `gorm:"column:deleted_at;type:timestamp with time zone;comment:删除时间" json:"deleted_at"`                               // 删除时间
	TenantID   *int64     `gorm:"column:tenant_id;type:bigint;index:privatemessage_tenant_id,priority:1;comment:租户ID" json:"tenant_id"`         // 租户ID
	Subject    *string    `gorm:"column:subject;type:character varying;comment:主题" json:"subject"`                                              // 主题
	Content    *string    `gorm:"column:content;type:character varying;comment:内容" json:"content"`                                              // 内容
	Status     *string    `gorm:"column:status;type:character varying;comment:消息状态" json:"status"`                                              // 消息状态
	SenderID   *int64     `gorm:"column:sender_id;type:bigint;comment:发送者用户ID" json:"sender_id"`                                                // 发送者用户ID
	ReceiverID *int64     `gorm:"column:receiver_id;type:bigint;comment:接收者用户ID" json:"receiver_id"`                                            // 接收者用户ID
}

// TableName PrivateMessage's table name
func (*PrivateMessage) TableName() string {
	return TableNamePrivateMessage
}
