// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysDict = "sys_dicts"

// SysDict mapped from table <sys_dicts>
type SysDict struct {
	ID            int32      `gorm:"column:id;type:integer;primaryKey;autoIncrement:true;index:dict_id,priority:1;comment:id" json:"id"` // id
	CreatedAt     *time.Time `gorm:"column:created_at;type:timestamp with time zone;comment:创建时间" json:"created_at"`                     // 创建时间
	UpdatedAt     *time.Time `gorm:"column:updated_at;type:timestamp with time zone;comment:更新时间" json:"updated_at"`                     // 更新时间
	DeletedAt     *time.Time `gorm:"column:deleted_at;type:timestamp with time zone;comment:删除时间" json:"deleted_at"`                     // 删除时间
	Status        *string    `gorm:"column:status;type:character varying;default:ON;comment:状态" json:"status"`                           // 状态
	CreateBy      *int64     `gorm:"column:create_by;type:bigint;comment:创建者ID" json:"create_by"`                                        // 创建者ID
	UpdateBy      *int64     `gorm:"column:update_by;type:bigint;comment:更新者ID" json:"update_by"`                                        // 更新者ID
	Remark        *string    `gorm:"column:remark;type:character varying;comment:备注" json:"remark"`                                      // 备注
	TenantID      *int64     `gorm:"column:tenant_id;type:bigint;index:dict_tenant_id,priority:1;comment:租户ID" json:"tenant_id"`         // 租户ID
	Key           *string    `gorm:"column:key;type:character varying;uniqueIndex:sys_dicts_key_key,priority:1;comment:字典键" json:"key"`  // 字典键
	Category      *string    `gorm:"column:category;type:character varying;comment:字典类型" json:"category"`                                // 字典类型
	CategoryDesc  *string    `gorm:"column:category_desc;type:character varying;comment:字典类型名称" json:"category_desc"`                    // 字典类型名称
	Value         *string    `gorm:"column:value;type:character varying;comment:字典值" json:"value"`                                       // 字典值
	ValueDesc     *string    `gorm:"column:value_desc;type:character varying;comment:字典值名称" json:"value_desc"`                           // 字典值名称
	ValueDataType *string    `gorm:"column:value_data_type;type:character varying;comment:字典值数据类型" json:"value_data_type"`               // 字典值数据类型
	SortID        *int32     `gorm:"column:sort_id;type:integer;comment:排序ID" json:"sort_id"`                                            // 排序ID
}

// TableName SysDict's table name
func (*SysDict) TableName() string {
	return TableNameSysDict
}
