// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysDictType = "sys_dict_types"

// SysDictType mapped from table <sys_dict_types>
type SysDictType struct {
	ID          int32          `gorm:"column:id;type:integer;primaryKey;autoIncrement:true;index:dict_id,priority:1;comment:id" json:"id"`                       // id
	CreatedAt   time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null;comment:创建时间" json:"created_at"`                                  // 创建时间
	UpdatedAt   *time.Time     `gorm:"column:updated_at;type:timestamp with time zone;comment:更新时间" json:"updated_at"`                                           // 更新时间
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone;index:idx_sys_dicts_deleted_at,priority:1;comment:删除时间" json:"deleted_at"` // 删除时间
	Status      *string        `gorm:"column:status;type:character varying;not null;default:ON;comment:状态" json:"status"`                                        // 状态
	CreateBy    int64          `gorm:"column:create_by;type:bigint;not null;comment:创建者ID" json:"create_by"`                                                     // 创建者ID
	UpdateBy    *int64         `gorm:"column:update_by;type:bigint;comment:更新者ID" json:"update_by"`                                                              // 更新者ID
	TenantID    int64          `gorm:"column:tenant_id;type:bigint;not null;index:dict_tenant_id,priority:1;comment:租户ID" json:"tenant_id"`                      // 租户ID
	SortOrder   *int16         `gorm:"column:sort_order;type:smallint;comment:排序ID" json:"sort_order"`                                                           // 排序ID
	DeletedBy   *int32         `gorm:"column:deleted_by;type:integer" json:"deleted_by"`
	TypeCode    string         `gorm:"column:type_code;type:character varying(255);not null" json:"type_code"`
	TypeName    string         `gorm:"column:type_name;type:character varying(255);not null" json:"type_name"`
	IsEnabled   bool           `gorm:"column:is_enabled;type:boolean;not null" json:"is_enabled"`
	Description *string        `gorm:"column:description;type:character varying(255);comment:字典描述" json:"description"` // 字典描述
}

// TableName SysDictType's table name
func (*SysDictType) TableName() string {
	return TableNameSysDictType
}
