// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysRole = "sys_roles"

// SysRole mapped from table <sys_roles>
type SysRole struct {
	ID        int32      `gorm:"column:id;type:integer;primaryKey;autoIncrement:true;index:role_id,priority:1;comment:id" json:"id"`    // id
	CreatedAt *time.Time `gorm:"column:created_at;type:timestamp with time zone;comment:创建时间" json:"created_at"`                        // 创建时间
	UpdatedAt *time.Time `gorm:"column:updated_at;type:timestamp with time zone;comment:更新时间" json:"updated_at"`                        // 更新时间
	DeletedAt *time.Time `gorm:"column:deleted_at;type:timestamp with time zone;comment:删除时间" json:"deleted_at"`                        // 删除时间
	Status    *string    `gorm:"column:status;type:character varying;default:ON;comment:状态" json:"status"`                              // 状态
	CreateBy  *int64     `gorm:"column:create_by;type:bigint;comment:创建者ID" json:"create_by"`                                           // 创建者ID
	UpdateBy  *int64     `gorm:"column:update_by;type:bigint;comment:更新者ID" json:"update_by"`                                           // 更新者ID
	Remark    *string    `gorm:"column:remark;type:character varying;comment:备注" json:"remark"`                                         // 备注
	TenantID  *int64     `gorm:"column:tenant_id;type:bigint;index:role_tenant_id,priority:1;comment:租户ID" json:"tenant_id"`            // 租户ID
	Name      *string    `gorm:"column:name;type:character varying;uniqueIndex:sys_roles_name_key,priority:1;comment:角色名称" json:"name"` // 角色名称
	Code      *string    `gorm:"column:code;type:character varying;index:role_code,priority:1;comment:角色标识" json:"code"`                // 角色标识
	SortID    *int32     `gorm:"column:sort_id;type:integer;comment:排序ID" json:"sort_id"`                                               // 排序ID
	Menu      *string    `gorm:"column:menus;type:jsonb;comment:分配的菜单列表" json:"menus"`                                                  // 分配的菜单列表
	API       *string    `gorm:"column:apis;type:jsonb;comment:分配的API列表" json:"apis"`                                                   // 分配的API列表
	ParentID  *int32     `gorm:"column:parent_id;type:integer;comment:上一层角色ID" json:"parent_id"`                                        // 上一层角色ID
}

// TableName SysRole's table name
func (*SysRole) TableName() string {
	return TableNameSysRole
}
