// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysMenu = "sys_menus"

// SysMenu mapped from table <sys_menus>
type SysMenu struct {
	ID        int32      `gorm:"column:id;type:integer;primaryKey;autoIncrement:true;comment:id" json:"id"`                                            // id
	Status    *string    `gorm:"column:status;type:character varying;default:ON;comment:状态" json:"status"`                                             // 状态
	CreatedAt *time.Time `gorm:"column:created_at;type:timestamp with time zone;comment:创建时间" json:"created_at"`                                       // 创建时间
	UpdatedAt *time.Time `gorm:"column:updated_at;type:timestamp with time zone;comment:更新时间" json:"updated_at"`                                       // 更新时间
	DeletedAt *time.Time `gorm:"column:deleted_at;type:timestamp with time zone;comment:删除时间" json:"deleted_at"`                                       // 删除时间
	CreateBy  *int64     `gorm:"column:create_by;type:bigint;comment:创建者ID" json:"create_by"`                                                          // 创建者ID
	UpdateBy  *int64     `gorm:"column:update_by;type:bigint;comment:更新者ID" json:"update_by"`                                                          // 更新者ID
	Remark    *string    `gorm:"column:remark;type:character varying;comment:备注" json:"remark"`                                                        // 备注
	Type      *string    `gorm:"column:type;type:character varying;default:MENU;comment:菜单类型 FOLDER: 目录 MENU: 菜单 BUTTON: 按钮" json:"type"`              // 菜单类型 FOLDER: 目录 MENU: 菜单 BUTTON: 按钮
	Path      *string    `gorm:"column:path;type:character varying;comment:路径,当其类型为'按钮'的时候对应的数据操作名,例如:/user.service.v1.UserService/Login" json:"path"` // 路径,当其类型为'按钮'的时候对应的数据操作名,例如:/user.service.v1.UserService/Login
	Redirect  *string    `gorm:"column:redirect;type:character varying;comment:重定向地址" json:"redirect"`                                                 // 重定向地址
	Alias_    *string    `gorm:"column:alias;type:character varying;comment:路由别名" json:"alias"`                                                        // 路由别名
	Name      *string    `gorm:"column:name;type:character varying;comment:路由命名，然后我们可以使用 name 而不是 path 来传递 to 属性给 <router-link>。" json:"name"`         // 路由命名，然后我们可以使用 name 而不是 path 来传递 to 属性给 <router-link>。
	Component *string    `gorm:"column:component;type:character varying;comment:前端页面组件" json:"component"`                                              // 前端页面组件
	Metum     *string    `gorm:"column:meta;type:jsonb;comment:前端页面组件" json:"meta"`                                                                    // 前端页面组件
	ParentID  *int32     `gorm:"column:parent_id;type:integer;comment:上一层菜单ID" json:"parent_id"`                                                       // 上一层菜单ID
}

// TableName SysMenu's table name
func (*SysMenu) TableName() string {
	return TableNameSysMenu
}
