// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysTask = "sys_tasks"

// SysTask mapped from table <sys_tasks>
type SysTask struct {
	ID          int32      `gorm:"column:id;type:integer;primaryKey;autoIncrement:true;index:task_id,priority:1;comment:id" json:"id"`                      // id
	CreatedAt   *time.Time `gorm:"column:created_at;type:timestamp with time zone;comment:创建时间" json:"created_at"`                                          // 创建时间
	UpdatedAt   *time.Time `gorm:"column:updated_at;type:timestamp with time zone;comment:更新时间" json:"updated_at"`                                          // 更新时间
	DeletedAt   *time.Time `gorm:"column:deleted_at;type:timestamp with time zone;comment:删除时间" json:"deleted_at"`                                          // 删除时间
	CreateBy    *int64     `gorm:"column:create_by;type:bigint;comment:创建者ID" json:"create_by"`                                                             // 创建者ID
	UpdateBy    *int64     `gorm:"column:update_by;type:bigint;comment:更新者ID" json:"update_by"`                                                             // 更新者ID
	Remark      *string    `gorm:"column:remark;type:character varying;comment:备注" json:"remark"`                                                           // 备注
	TenantID    *int64     `gorm:"column:tenant_id;type:bigint;index:task_tenant_id,priority:1;comment:租户ID" json:"tenant_id"`                              // 租户ID
	Type        *string    `gorm:"column:type;type:character varying;comment:任务类型" json:"type"`                                                             // 任务类型
	TypeName    *string    `gorm:"column:type_name;type:character varying;uniqueIndex:sys_tasks_type_name_key,priority:1;comment:任务执行类型名" json:"type_name"` // 任务执行类型名
	TaskPayload *string    `gorm:"column:task_payload;type:jsonb;comment:任务数据" json:"task_payload"`                                                         // 任务数据
	CronSpec    *string    `gorm:"column:cron_spec;type:character varying;comment:cron表达式" json:"cron_spec"`                                                // cron表达式
	TaskOption  *string    `gorm:"column:task_options;type:jsonb;comment:任务选项" json:"task_options"`                                                         // 任务选项
	Enable      *bool      `gorm:"column:enable;type:boolean;comment:启用/禁用任务" json:"enable"`                                                                // 启用/禁用任务
}

// TableName SysTask's table name
func (*SysTask) TableName() string {
	return TableNameSysTask
}
