// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysAPIResource = "sys_api_resources"

// SysAPIResource mapped from table <sys_api_resources>
type SysAPIResource struct {
	ID                int32      `gorm:"column:id;type:integer;primaryKey;autoIncrement:true;index:apiresource_id,priority:1;comment:id" json:"id"` // id
	CreatedAt         *time.Time `gorm:"column:created_at;type:timestamp with time zone;comment:创建时间" json:"created_at"`                            // 创建时间
	UpdatedAt         *time.Time `gorm:"column:updated_at;type:timestamp with time zone;comment:更新时间" json:"updated_at"`                            // 更新时间
	DeletedAt         *time.Time `gorm:"column:deleted_at;type:timestamp with time zone;comment:删除时间" json:"deleted_at"`                            // 删除时间
	CreateBy          *int64     `gorm:"column:create_by;type:bigint;comment:创建者ID" json:"create_by"`                                               // 创建者ID
	UpdateBy          *int64     `gorm:"column:update_by;type:bigint;comment:更新者ID" json:"update_by"`                                               // 更新者ID
	Description       *string    `gorm:"column:description;type:character varying;comment:描述" json:"description"`                                   // 描述
	Module            *string    `gorm:"column:module;type:character varying;comment:所属业务模块" json:"module"`                                         // 所属业务模块
	ModuleDescription *string    `gorm:"column:module_description;type:character varying;comment:业务模块描述" json:"module_description"`                 // 业务模块描述
	Operation         *string    `gorm:"column:operation;type:character varying;comment:接口操作名" json:"operation"`                                    // 接口操作名
	Path              *string    `gorm:"column:path;type:character varying;comment:接口路径" json:"path"`                                               // 接口路径
	Method            *string    `gorm:"column:method;type:character varying;comment:请求方法" json:"method"`                                           // 请求方法
}

// TableName SysAPIResource's table name
func (*SysAPIResource) TableName() string {
	return TableNameSysAPIResource
}
