// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTenant = "tenants"

// Tenant mapped from table <tenants>
type Tenant struct {
	ID             int32      `gorm:"column:id;type:integer;primaryKey;autoIncrement:true;index:tenant_id,priority:1;comment:id" json:"id"` // id
	CreatedAt      *time.Time `gorm:"column:created_at;type:timestamp with time zone;comment:创建时间" json:"created_at"`                       // 创建时间
	UpdatedAt      *time.Time `gorm:"column:updated_at;type:timestamp with time zone;comment:更新时间" json:"updated_at"`                       // 更新时间
	DeletedAt      *time.Time `gorm:"column:deleted_at;type:timestamp with time zone;comment:删除时间" json:"deleted_at"`                       // 删除时间
	Status         *string    `gorm:"column:status;type:character varying;default:ON;comment:状态" json:"status"`                             // 状态
	CreateBy       *int64     `gorm:"column:create_by;type:bigint;comment:创建者ID" json:"create_by"`                                          // 创建者ID
	UpdateBy       *int64     `gorm:"column:update_by;type:bigint;comment:更新者ID" json:"update_by"`                                          // 更新者ID
	Remark         *string    `gorm:"column:remark;type:character varying;comment:备注" json:"remark"`                                        // 备注
	Name           *string    `gorm:"column:name;type:character varying;comment:租户名称" json:"name"`                                          // 租户名称
	Code           *string    `gorm:"column:code;type:character varying;comment:租户编号" json:"code"`                                          // 租户编号
	MemberCount    *int32     `gorm:"column:member_count;type:integer;comment:成员数" json:"member_count"`                                     // 成员数
	SubscriptionAt *time.Time `gorm:"column:subscription_at;type:timestamp with time zone;comment:订阅时间" json:"subscription_at"`             // 订阅时间
	UnsubscribeAt  *time.Time `gorm:"column:unsubscribe_at;type:timestamp with time zone;comment:取消订阅时间" json:"unsubscribe_at"`             // 取消订阅时间
}

// TableName Tenant's table name
func (*Tenant) TableName() string {
	return TableNameTenant
}
