// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID            int32      `gorm:"column:id;type:integer;primaryKey;autoIncrement:true;index:user_id,priority:1;comment:id" json:"id"`           // id
	CreateBy      *int64     `gorm:"column:create_by;type:bigint;comment:创建者ID" json:"create_by"`                                                  // 创建者ID
	UpdateBy      *int64     `gorm:"column:update_by;type:bigint;comment:更新者ID" json:"update_by"`                                                  // 更新者ID
	CreatedAt     *time.Time `gorm:"column:created_at;type:timestamp with time zone;comment:创建时间" json:"created_at"`                               // 创建时间
	UpdatedAt     *time.Time `gorm:"column:updated_at;type:timestamp with time zone;comment:更新时间" json:"updated_at"`                               // 更新时间
	DeletedAt     *time.Time `gorm:"column:deleted_at;type:timestamp with time zone;comment:删除时间" json:"deleted_at"`                               // 删除时间
	Remark        *string    `gorm:"column:remark;type:character varying;comment:备注" json:"remark"`                                                // 备注
	Status        *string    `gorm:"column:status;type:character varying;default:ON;comment:状态" json:"status"`                                     // 状态
	TenantID      *int64     `gorm:"column:tenant_id;type:bigint;index:user_tenant_id,priority:1;comment:租户ID" json:"tenant_id"`                   // 租户ID
	Username      *string    `gorm:"column:username;type:character varying;uniqueIndex:users_username_key,priority:1;comment:用户名" json:"username"` // 用户名
	Nickname      *string    `gorm:"column:nickname;type:character varying;comment:昵称" json:"nickname"`                                            // 昵称
	Realname      *string    `gorm:"column:realname;type:character varying;comment:真实名字" json:"realname"`                                          // 真实名字
	Email         *string    `gorm:"column:email;type:character varying;comment:电子邮箱" json:"email"`                                                // 电子邮箱
	Mobile        *string    `gorm:"column:mobile;type:character varying;comment:手机号码" json:"mobile"`                                              // 手机号码
	Telephone     *string    `gorm:"column:telephone;type:character varying;comment:座机号码" json:"telephone"`                                        // 座机号码
	Avatar        *string    `gorm:"column:avatar;type:character varying;comment:头像" json:"avatar"`                                                // 头像
	Address       *string    `gorm:"column:address;type:character varying;comment:地址" json:"address"`                                              // 地址
	Region        *string    `gorm:"column:region;type:character varying;comment:国家地区" json:"region"`                                              // 国家地区
	Description   *string    `gorm:"column:description;type:character varying;comment:个人说明" json:"description"`                                    // 个人说明
	Gender        *string    `gorm:"column:gender;type:character varying;comment:性别" json:"gender"`                                                // 性别
	Authority     *string    `gorm:"column:authority;type:character varying;default:CUSTOMER_USER;comment:授权" json:"authority"`                    // 授权
	LastLoginTime *time.Time `gorm:"column:last_login_time;type:timestamp with time zone;comment:最后一次登录的时间" json:"last_login_time"`                // 最后一次登录的时间
	LastLoginIP   *string    `gorm:"column:last_login_ip;type:character varying;comment:最后一次登录的IP" json:"last_login_ip"`                           // 最后一次登录的IP
	OrgID         *int64     `gorm:"column:org_id;type:bigint;comment:部门ID" json:"org_id"`                                                         // 部门ID
	PositionID    *int64     `gorm:"column:position_id;type:bigint;comment:职位ID" json:"position_id"`                                               // 职位ID
	WorkID        *int64     `gorm:"column:work_id;type:bigint;comment:员工工号" json:"work_id"`                                                       // 员工工号
	Role          *string    `gorm:"column:roles;type:jsonb;comment:多角色角色码列表" json:"roles"`                                                        // 多角色角色码列表
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
