// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserCredential = "user_credentials"

// UserCredential mapped from table <user_credentials>
type UserCredential struct {
	ID             int32      `gorm:"column:id;type:integer;primaryKey;autoIncrement:true;index:usercredential_id,priority:1;comment:id" json:"id"`                                                                                 // id
	CreatedAt      *time.Time `gorm:"column:created_at;type:timestamp with time zone;comment:创建时间" json:"created_at"`                                                                                                               // 创建时间
	UpdatedAt      *time.Time `gorm:"column:updated_at;type:timestamp with time zone;comment:更新时间" json:"updated_at"`                                                                                                               // 更新时间
	DeletedAt      *time.Time `gorm:"column:deleted_at;type:timestamp with time zone;comment:删除时间" json:"deleted_at"`                                                                                                               // 删除时间
	TenantID       *int64     `gorm:"column:tenant_id;type:bigint;index:usercredential_tenant_id,priority:1;comment:租户ID" json:"tenant_id"`                                                                                         // 租户ID
	UserID         *int64     `gorm:"column:user_id;type:bigint;uniqueIndex:usercredential_user_id_identity_type_identifier,priority:1;index:usercredential_user_id,priority:1;comment:关联主表的用户ID" json:"user_id"`                   // 关联主表的用户ID
	IdentityType   *string    `gorm:"column:identity_type;type:character varying;uniqueIndex:usercredential_user_id_identity_type_identifier,priority:2;default:USERNAME;comment:认证方式类型" json:"identity_type"`                      // 认证方式类型
	Identifier     *string    `gorm:"column:identifier;type:character varying;uniqueIndex:usercredential_user_id_identity_type_identifier,priority:3;index:usercredential_identifier,priority:1;comment:身份唯一标识符" json:"identifier"` // 身份唯一标识符
	CredentialType *string    `gorm:"column:credential_type;type:character varying;default:PASSWORD_HASH;comment:凭证类型" json:"credential_type"`                                                                                      // 凭证类型
	Credential     *string    `gorm:"column:credential;type:character varying;comment:凭证" json:"credential"`                                                                                                                        // 凭证
	IsPrimary      *bool      `gorm:"column:is_primary;type:boolean;comment:是否主认证方式" json:"is_primary"`                                                                                                                             // 是否主认证方式
	Status         *string    `gorm:"column:status;type:character varying;default:ENABLED;comment:凭证状态" json:"status"`                                                                                                              // 凭证状态
	ExtraInfo      *string    `gorm:"column:extra_info;type:jsonb;comment:扩展信息" json:"extra_info"`                                                                                                                                  // 扩展信息
	ActivateToken  *string    `gorm:"column:activate_token;type:character varying;uniqueIndex:user_credentials_activate_token_key,priority:1;comment:激活账号用的令牌" json:"activate_token"`                                               // 激活账号用的令牌
	ResetToken     *string    `gorm:"column:reset_token;type:character varying;uniqueIndex:user_credentials_reset_token_key,priority:1;comment:重置密码用的令牌" json:"reset_token"`                                                        // 重置密码用的令牌
}

// TableName UserCredential's table name
func (*UserCredential) TableName() string {
	return TableNameUserCredential
}
